### ISSUE TITLE
BF: Random cloud generator - consolidation and enhancements

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1024]
**Description/Motivation**
There are currently two implementations for random point clouds that shall be consolidated. Furthermore, there are new feature requests to be implemented.

**Task list**

- [x] **0 Final decision on the surviving approach**
   - [ ] Candidate 1: bf.streams.stream.clouds.StreamMLProClouds
   - [x] Candidate 2: bf.streams.stream.clusters.StreamMLProClusterGenerator
- [x] **1 Review and decision of cloud generator to be kept/retired**
- [x] **2 Optional boundaries per feature**
    The optional specification of boundaries per feature shall be enabled. This enables benchmarking on unnormalized data. In particular, spatial (e.g. Euclidean) distances are distorted. The current implementation uses static boundaries specified in the constant attribute C_BOUNDARIES of class StreamMLProClusterGenerator.
    - [x] 1.1 Constructor: 
        - [x] new optional parameter p_boundaries_rescale
        - [x] new protected attribute self._boundaries, initialized from p_boundaries or C_BOUNDARIES
    - [x] 1.2 Method _get_next(): optional rescaling based on p_boundaries_rescale
- [x] **3 Collision**
    The clouds generated shall collide at a defined point...
- [x] **4 Counting and raising anomalies** (Devindi)
    - [x] Raising of events for anomalies
    - [x] Provision of the number of generated anomalies
- [x] **5 Public cluster statistics for tracking** 
- [x] **6 New parameter p_cluster_centers**
      ... enabling the definition of initial cluster centers
- [ ] **7 Deformation**
- [ ] **8 Enabling initial radii per cluster and feature**
- [x] **9 RTD: Update API**
