### ISSUE TITLE
Compatibility with Python 3.10-3.12

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1044]
**Description/Motivation**
Following the compatibility range of [NumPy 2.1.0](https://numpy.org/news/) the compatibility of MLPro for the Python versions 3.10 - 3.12 shall be ensured/validated.

**Task list**
- [x] **1 Update of workflow ci.yml and further files referring to Python versions**
- [x] **2 Validation/alignment of all functionalities**
- [x] **3 Check/update of all related extensions MLPro-Int-...**

**Cross references**
https://numpy.org/news/

**Comment by detlefarend** [comment]
@steveyuwono fyi

**Comment by detlefarend** [comment]
Issues for all MLPro-Int-* packages are created...

**Comment by detlefarend** [comment]
The official support of v 3.13 is postponed due to current [compatibility problems](https://github.com/fhswf/MLPro/actions/runs/11248438352) with numpy...
