### ISSUE TITLE
BF: PID Controller (SISO)

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1048]
**Description/Motivation**
A classic PID controller shall be designed and implemented.

**Task list**
- [x] 1. Class design
- [x] 2. Implementation
    - [x] 2.1 Class bf.control.controllers.PIDController 
- [ ] 3. Howto(s) to demonstrate the use
    - [ ] 3.1 test/howtos/bf/howto_bf_control_101_pid_controller_standalone.py 
    - [ ] 3.2 test/howtos/bf/howto_bf_control_102_pid_controller_embedded.py 
    - [ ] 3.3 test/howtos/bf/howto_bf_control_103_pid_controller_cascaded.py 
- [ ] 4. RTD documentation
    - [ ] 4.1 Pool object
    - [ ] 4.2 API
    - [ ] 4.3 Related howtos 

**Related issues**
#1046 #1080 

**Cross references**
[Wikipedia: Proportional–integral–derivative controller](https://en.wikipedia.org/wiki/Proportional%E2%80%93integral%E2%80%93derivative_controller)

**Comment by detlefarend** [comment]
Hi @amesin13, the class and howto mentioned above have already been added. You can start implementing both. The howto shall demonstrate/validate the correct behavior of the pid controller on a basic level by using method **compute_action** directly. Further howtos shall showcase the pid controller as part of a control loop.
