### ISSUE TITLE
BF: New class bf.math.geometry.Crosshair

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1078]
**Description/Motivation**
The new class bf.math.geometry.Crosshair shall take over the crosshair functionality from oa.streams.tasks.clusteranalyzers.clusters.properties.Centroid. This, in turn, shall inherit from Crosshair. This enables simple crosshair functionality for a wider range of applications.

**Task list**
- [x] **1. New class bf.math.geometry.Crosshair**
- [x] **2. Class oa.streams...Centroid: inherited from Crosshair**
- [x] **3. Howtos demonstrating the use**
    - [x] howto_bf_math_035_geometry_crosshair_2d.py
    - [x] howto_bf_math_036_geometry_crosshair_3d.py 
- [ ] **4. Update of all related class diagrams**
- [ ] **5. Update RTD**

**Related issues**
#...

**Cross references**
...
