### ISSUE TITLE
BF-Streams: Systematics for workflows in workflows

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1086]
**Description/Motivation**
Stream workflows added as tasks to superior workflows still need to be implemented/validated. The following questions and aspects need to be examined:

**Task list**
- [ ] 1. Question: do all workflows share the same (master) shared object (unlike bf.control)?
- [ ] 2. If not: what is to be done to hand over instances from task to workflow to task?
- [ ] 3. Pooling of senseful workflows
    - [ ] 3.1 Boundary-Detector, MinMax-Normalizer 
- [ ] 4. Suitable howtos 

**Related issues**
#1046 

**Cross references**
Custom method bf.mt.Task._on_finished() and its implementation in class bf.control.ControlWorkflow
