### ISSUE TITLE
BF-Control: Master view/cockpit

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1089]
**Description/Motivation**
A master view shall be designed/implemented with the following features:
- Plot of system state and setpoint
- Control buttons: start, stop, pause, step 1, step 10

**Technical approach**
The functionality mentioned could be implemented in the classes StreamWorkflow (control buttons) and ControlWorkflow (particular control master plot).

**Task list**
- [ ] 1. Design extension StreamWorkflow/ControlWorkflow
- [ ] 2. Class StreamWorkflow: introduction of control buttons
- [ ] 3. Class ControlWorkflow: specific plot as described
