### ISSUE TITLE
OA: 2D/3D visualization for group anomalies

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1096]
**Description/Motivation**
Class oa.streams.tasks.anomalydetectors.anomalies.group.GroupAnomaly shall be extended by plot functionality in 2D and 3D view.

**Task list**
- [ ] 1. Implementation of method GroupAnomaly._update_plot_2d 
- [ ] 2. Implementation of method GroupAnomaly._update_plot_3d
- [ ] 3. Suitable howtos (see mlpro-int-scikit-learn)
