### ISSUE TITLE
BF: Plot window arrangement - storage/recovery of window size and position

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1114]
**Description/Motivation**
The plot windows created by class mlpro.bf.plot.Plottable need to be placed/resized manually each time a program is started. To improve the user experience of MLPro's plot mechanism, the class shall be extended by functionality for storing and recovering the size and position of a window. 

**Task list**
- [x] **1. Underlying functions**
    - [x] 1.1 Class ConfigFile
            ... storing (plot) configuration data in a local JSON file
    - [x] 1.2 Template class PlotBackend
        - [x] 1.2.1 Systematics to deal with different backends
        - [x] 1.2.2 Systematics to deal with different OS
    - [x] 1.3 Implementation PlotBackendTkAgg
        - [x] 1.3.1 Linux/Default
        - [x] 1.3.2 Windows
- [x] **2. Explore/ensure stable proceedings for backend TkAgg under all OS platforms**
    - [x] 2.1 Method Plottable._init_figure()
        - [x] 2.1.1 Get and store the size and position of the window in a local (hidden) file in the user's home directory
        - [x] 2.1.2 Set window title
        - [x] 2.1.3 Force foreground
            - [ ] Open question: why does forcing the foreground need a pause of 2000ms while the first plot update brings all windows on top of the screen. What Matplotlib/Tkinter command is needed to flush the foreground command?
        - [x] 2.1.4 Valid control of the matplotlib event-loop (plt.show vs. plt.pause), window refresh, ...
- [x] **3. Extensive validation**
    - [x]  3.1 Linux
        - [x] Related howtos and paper examples
        - [ ] Versions of matplotlib/numpy
    - [x]  3.2 Windows
        - [x] Related howtos and paper examples
        - [ ] Versions of matplotlib/numpy
    - [x] 3.3 MacOS
        - [x] Related howtos and paper examples
        - [ ] Versions of matplotlib/numpy
- [x] **4. Update RTD**
    - [x]  4.1 Class diagrams and API
