### ISSUE TITLE
OA: Boundary detector - Improvement of reverse adaptation

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1118]
**Description/Motivation**
In the current implementation of class mlpro.oa.streams.tasks.BoundaryDetector, reverse adaptation is event-based. It listens to the event C_DATA_REMOVED of a prior sliding window and applies its full boundary detection functionality if such an event occurs. Once a previous window buffer is filled, every incoming instance causes the removal of an obsolete one, which triggers the event above.

Reverse adaptation of the boundary detector shall be turned into an online functionality: incoming obsolete instances shall be observed feature-wise for touching existing boundaries. Nothing is to be done if no feature value of an outdated instance touches a boundary. Otherwise, a full determination of the upper/lower boundary of **this** feature is to be carried out using a regarding functionality of the window task.

The improvements can be summarized as follows:

1.  Reverse adaptation by reducing boundaries based on outdated instances becomes more rare
2. The effort of reverse adaptation is lowered
3. Since a boundary detector is often part of an adaptation cascade with a min-max normalizer, cluster analyzer, anomaly detector, etc., the improvements above directly affect the overall performance of the entire workflow

**Task list**
- [ ] 1. New base class BoundaryDetectorBase
    - [ ] 1.1 Implementation of entire adaptation logic except reverse adaptation 
- [ ] 2. Class BoundaryDetector
    - [ ] 2.1 Implementation of method _adapt_reverse()
    - [ ] 2.2a New parameter **p_window_callback**
    - [ ] 2.2b Alternative: buffer registers its callback service at the shared object
- [ ] 3. Benchmarking
    - [ ] Comparison of event-oriented vs. reverse adaptation
- [ ] 4. RTD
    - [ ] Update class diagrams and API
    - [ ] Update of related howtos
