### ISSUE TITLE
BF-Plot: Default plot-backend QtAgg

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1119]
**Description/Motivation**
Currently, TkAgg is the default backend since it is part of the Python language and totally platform-independent. QtAgg, in turn, promises a higher performance (20-50%) and is also seamlessly integrated and platform-independent.

**Task list**
- [x] 1. Make QtAgg the default and TkAgg the fallback backend
- [x] 2. New class bf.plot.backends.qtagg.PlotBackendQtAgg
- [x] 3. Benchmarking howtos for 2D, 3D and nD Visualization

**Related issues**
#...

**Cross references**
...
