### ISSUE TITLE
BF: Multitasking

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#391]
A new module **mt** for multitasking shall be added to the basic functions of MLPro. It shall provide a standardized high-level multitasking (=multithreading/multiprocessing) interface for asynchronous tasks that optionally exchange data using a shared object.

**Tasks:**

- [x] New module mlpro.bf.mt
- [x] OO Design / class diagram
- [x] Template class "Shared" for shared objects
- [x] Property class "Async"
- [x] Template class "Task"
- [x] Class "Workflow"
- [x] Suitable howtos 
    - [x] Howto BF-MT-001: Parallel Algorithms
    - [x] Howto BF-MT-002: Tasks and Workflows
- [x] RTD documentation
    - [x] Howto BF-MT-001
    - [x] Howto BF-MT-002

**Design aspects:**

- SRP (short running process) vs. LRP (long running process)
- Shared objects (access control, concurrency)
- Messaging
- Event handling

**Cross references:**
https://docs.python.org/3/library/multiprocessing.html
https://docs.python.org/3/library/multiprocessing.html#synchronization-primitives
https://docs.python.org/3/library/concurrent.futures.html#module-concurrent.futures
