### ISSUE TITLE
Marketplace for MLPro extensions

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#413]
**Description/Motivation**
MLPro extensions are separate 3rd party GitHub repos that provide additional functionalities around/on top of MLPro. They can be created by everyone but please in a standardized way. A new Section **Extensions** or **Marketeplace** on RTD could list all public repos forked from this repo...

**Task list**
- [ ] **1. New template repository**
   - [x] New repo **fhswf/MLPro-Extension** as template (for the moment: private)
   - [ ] Template files
      - [ ] Readme.md
         - [ ] Various badges, in particular for download statistics (see also: #494)  
      - [ ] Issue templates
      - [ ] Python module
      - [ ] Python howto file
   - [ ] Default folder structure
   - [ ] PyPI deployment action
   - [ ] Anaconda deployment action
   
- [x] **2. Cyclic detection of new repositories**
     Github workflows can be triggered by [schedules](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule). This can be used to start a special workflow to determine new repositories
   - [x] New subfolder "marketplace"
   - [x] New file "whitelist" within (manual maintenance in branch main)
   - [x] New file "blacklist" within (manual maintenance in branch main)
   - [x] Templates for issue body/comment, owner and repo descriptions
   - [x] Python module 'update_marketplace.py
        - [x] Detect all extensions with topic "mlpro-extension"
        - [x] If the repo is neither whitelisted nor blacklisted, an issue labelled "pending-extension" is to be created.
        - [x] If the repo is blacklisted, it is to be removed from RTD 
        - [x] If the repo is whitelisted, it is to be added/updated to RTD
   - [x] Workflow "Marketplace Update" 

- [ ] **3. RTD MLPro: New section "Extension Hub"**
   - [ ] Explanations/Tutorials for own extensions
   - [x] Submenu for extensions, separated by organizations and single users, grouped by owners

**Cross References**
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
https://github.com/orgs/community/discussions/26672
