### ISSUE TITLE
BF: Restructuring of mathematical classes

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#420]
**Description/Motivation**
In preparation of further mathematical/numerical implementations module bf.math shall be conferted to a backwards compatible sub-package.

**Task list**
- [x] 1. New folder ./bf/math
- [x] 2. Shift ./bf/math.py to new folder and rename it to basics.py
- [x] 3. New file ./bf/math/__init__.py and import module basics here
- [x] 4. Check whether the howtos are still running
