### ISSUE TITLE
Update Gym Wrapper: following v0.26.1 or latest

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#429]
**Description/Motivation**
Update the gym wrapper following the latest version of Gym library. Some howto files are incompatible if the gym is in version 0.26.0 or higher.

**Task list**
- [ ] Check WrEnvGYM2MLPro
- [ ] Check WrEnvMLPro2GYM
- [ ] Check SB3 wrapper
- [ ] Check PZoo wrapper
- [ ] Check related howto files

**Related issues**
#...

**Cross references**
https://github.com/openai/gym/releases

**Comment by detlefarend** [comment]
As discussed today we should rather copy/paste the current state and make it compatible to Gymnasium....
