### ISSUE TITLE
MLPro project templates

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#430]
**Task list**
- [x] 1. Template for class diagrams (drawio)
- [x] 2. Template for howtos
- [x] 3. Template for modules
- [ ] 4. Template for rtd wrapper descriptions (.rst)
- [x] 5. Template for rtd environment descriptions (.rst)
- [x] 6. Template for rtd howto descriptions (.rst)
- [x] 7. Template for rtd module descrptions (.rst)
- [x] 8. Suitable incorporation in rtd documentation

**Comment by detlefarend** [comment]
Hi @steveyuwono @rizkydiprasetya @laxmikantbaheti, I just added a new folder ./templates to branch rtd_1.0.0 and reworked/completed the content. In rtd I removed subsection Templates from the API reference and added an annotation with a link to appendix3->contribution. This link will work after merging to main.

Please use the templates for new 
- howtos and their rtd description 
- modules and their class diagram and rtd description
- rtd descriptions of rl environments

Thx!
