### ISSUE TITLE
Extension of howto unit tests: PyPy conformity

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#433]
**Description/Motivation**
This issue shall ensure MLPro's compatibility to the faster Python derivate PyPy.

**Task list**
- [ ] 1. All howto files: reduction of runtime in unit test mode to an absolute necessary minimum
- [ ] 2. Extension of unit test by a second run under PyPy
- [ ] 3. Logging of speed gain by using PyPy
- [ ] 4. RTD documentation, introduction: hint for PyPy conformity (and speed gain)

**Cross references**
https://www.pypy.org/
https://github.com/fhswf/MLPro/tree/rizkydiprasetya/issue433/.github/workflows

**Comment by rizkydiprasetya** [comment]
SB3 wrapper

**Comment by rizkydiprasetya** [comment]
The results are the following without pytorch:
- Pypy 3.8 : Success 
- Pypy 3.9 : Failed due to Scipy Package (I have to check this locally, because the installation of Scipy was succeed)

Note: Some of the packages are not available as binary, so those packages need to be compiled and it take times. This could be solved with pre-compiled docker container. The run can be checked here: 
https://github.com/fhswf/MLPro/actions/runs/3483988002

**Comment by detlefarend** [comment]
I've found some articles that suggest using anaconda packages in combination with pypy might be beneficial:
https://www.pypy.org/compat.html
https://www.pypy.org/posts/2022/11/pypy-and-conda-forge.html

**Comment by rizkydiprasetya** [comment]
Then, it is in conda environment. Maybe we can leave some note for the user, for pypy, they need to use conda.

**Comment by rizkydiprasetya** [comment]
with conda-forge, there is another problem with the scikit-learn package. It is successfully installed, but the error says, it is not installed properly by conda. And also another problem with pygame in rl_wp_003 example.

Here is the runner:
https://github.com/fhswf/MLPro/actions/runs/3487389868

**Comment by detlefarend** [comment]
As discussed in our today's meeting: let' recap this topic and setup a new option for pip to install mlpro with all 3rd-party packages that are compatible to pypy....
