### ISSUE TITLE
SL: Initial design

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#434]
**Description/Motivation**
Initial class **design** for new sub-framework MLPro-SL for (offline) supervised learning. 

**Task list**
- [ ] Initial class landscape
  - [ ] Reuse
     - [ ] bf.ml
     - [ ] bf.events
     - [ ] bf.mt
     - [ ] bf.math
- [ ] Concept for (Big) data sets (see: bf.streams)
   - [ ] Classes DataSetProvider, DataSet (see also: classes StreamProvider, Stream)
   - [ ] Relation to buffers (bf.data)
- [ ] Definition of wrappers for relevant packages

**Keywords**
data set, adaptive function, feed forward neural network, cnn, rbf net, mlp, gan, onnx, ...
 
**Related issues**
#...

**Cross references**
[ONNX](https://onnx.ai/)
[Generative Adversarial Network (GAN)](https://en.wikipedia.org/wiki/Generative_adversarial_network)
[Radial Basis Function (RBF) Network](https://en.wikipedia.org/wiki/Radial_basis_function_network)
[Deep Learning](https://en.wikipedia.org/wiki/Deep_learning)
[Convolutional Neural Network](https://en.wikipedia.org/wiki/Convolutional_neural_network)

**Comment by detlefarend** [comment]
Hi @steveyuwono @rizkydiprasetya @laxmikantbaheti @marlonloeppenberg, I just prepared a new issue for the initial design and concepts of the sub-framework MLPro-SL for (offline) supervised learning. Please add yourself as assignee if you are interested in designing it. During this issue we really just design (OOD). We don't implement something.

Class diagram already exists. To avoid collisions, let the others know, if you are working on it. Currently I am adding some first things...

Branch is **sl_design**, pull request follows...

**Comment by detlefarend** [comment]
@steveyuwono @rizkydiprasetya @laxmikantbaheti @marlonloeppenberg: I've just kicked it off. Class diagram is updated.

@laxmikantbaheti If you like you could think of a GAN concept. See class diagram.

**Comment by steveyuwono** [comment]
> Hi @detlefarend @steveyuwono , I was working with SL last week and came to a finding. The adapt offline method, which supposedly is the method to train an adaptive function with an offline dataset/buffer. However, I think, the current implementation for sampling or forward() does not handle the batch size properly. Two probable causes:
> 
> 1. The adapt offline method forwards the dataset attribute of the trainer and not the dataset. And thus the dataset when indexed returns an instance and not dataset. I'm sorry if the it is the expected behavior.
> 2. In the forward method, i see there's batch size handled. however, when I debug the howto for mbrl for gridworld, the batch size dimension comes because the the state values are again wrapped in an empty list, in the input_preproc method. And, thus only one instance is passed at each forward and optimize cycle of _adapt_offline. Coincidentally, it's adapting online 😅. Please let me know if I'm wrong.
> 
> Thanks!

Hi Laxmikant,

thank you for your comments.

are you dealing with PyTorch-based MLP? The difference between _adapt_online and _adapt_offline is the input, where adapt offline has already a dataset or a buffer to be processed. Meanwhile, adapt online has only a set of input and output as the method’s input, then this set is stored in a buffer. Later on, if the buffer is full, then we begin the adaptation by sampling data from the buffer and set them as inputs of the adapt offline.

Regarding your first question, in this case, trainer is actually a splitted dataset. Once we call self._buffer.sampling(), it uses the pytorch sampling functionalities and returns two splitted datasets (dataset for training -> trainer, dataset for testing -> tester). The trainer is a dictionary cosists of two keys, such as input and output. Each key has a dataset which has been sampled, I believe the format is a tensor with np.array. Is it correct? If you use the adapt offline without adapt online, then I expect to use the same input format as trainer or tester in the adapt online. Becuase at the moment we have not yet finalized the standard of dataset in MLPro-SL. Otherwise, you can just simple redefine the method.

Concerning your second question, i think the batch size is only to get the size of the p_input in a scalar value. I did not get about the empty list, can you elaborate this or create a debug issue if something is not right? Then, i can fix it after my holiday. Because the input_preproc is just to transform Element to torch.tensor. The adapt offline does not only handle one instance but the whole dataset. I think, p_dataset["input"].dataset[0] is not returning a single instance, am I right? It is supposed to be a tensor with np.array.

Are the states values of grid world completely empty? If i’m not mistaken, most of the values are mostly zero, only the current position and target position are not zero.

I hope this is helpful. I have noted this issue. I will check this after my holiday. Thank you anyway!

**Comment by laxmikantbaheti** [comment]
Hi @steveyuwono , thanks for explanation. You are right. The entire process works as you mentioned, but the the data loading and batch size. Sorry I blundered with the words dataset and data-loader in last comment. I will create an issue and describe in more detail there.

**Comment by laxmikantbaheti** [comment]
Hi everyone, @steveyuwono , @rizkydiprasetya , @detlefarend . @syam47 , I am creating a new branch for Supervised learning. I need initial implementations in SL for some experiments. I will create some initial designs and start doing some minor extensions. If interesting to all, I can share my existing ideas about it and optimize it together, in one of our next common meetings. Maybe next Friday.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , @steveyuwono 
I think I have finished my development in SL. I think I will create a different issue, separate for a new discussion space. The next step I wish to do is discuss about some developments in Hyperparameter Tuner wrappers. However, before going directly into that, I would like the current progress to be reviewed if possible, and merged in Systems branch, so that I can proceed with my further developments.
I will create a separate issue...

**Comment by detlefarend** [comment]
> Hi @detlefarend , @steveyuwono I think I have finished my development in SL. I think I will create a different issue, separate for a new discussion space. The next step I wish to do is discuss about some developments in Hyperparameter Tuner wrappers. However, before going directly into that, I would like the current progress to be reviewed if possible, and merged in Systems branch, so that I can proceed with my further developments. I will create a separate issue...

Hi Laxmikant, that sounds promising and I am very curious about your progress. I propose that we schedule an appointment where you present and explain your work, followed by a common review. What about Thursday in the lab?

**Comment by detlefarend** [comment]
Regarding HP and their tuning: this is very fundamental and universal. We should discuss any changes in advance. Let's put it on the agenda for the appointment.

**Comment by laxmikantbaheti** [comment]
> Regarding HP and their tuning: this is very fundamental and universal. We should discuss any changes in advance. Let's put it on the agenda for the appointment.

Sure.

**Comment by laxmikantbaheti** [comment]
> > Hi @detlefarend , @steveyuwono I think I have finished my development in SL. I think I will create a different issue, separate for a new discussion space. The next step I wish to do is discuss about some developments in Hyperparameter Tuner wrappers. However, before going directly into that, I would like the current progress to be reviewed if possible, and merged in Systems branch, so that I can proceed with my further developments. I will create a separate issue...
> 
> Hi Laxmikant, that sounds promising and I am very curious about your progress. I propose that we schedule an appointment where you present and explain your work, followed by a common review. What about Thursday in the lab?

Hi @detlefarend sure, we can do this...

**Comment by steveyuwono** [comment]
Hi @laxmikantbaheti , I am also fine with the meeting on Thursday. I will review the changes before the meeting, as per request in #782 and inform you.

**Comment by detlefarend** [comment]
Hi guys, I've put this on hold because currently no one works on this actively. Despite of this, we should rather focus on our upcoming releases for OA, OA-Systems, OA-AD.
