### ISSUE TITLE
RL: Class TrainingRL - Acceleration by running evaluation episodes asynchronously

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#438]
**Description/Motivation**
An RL/GT training can be accelerated by running evaluation episodes as separate processes.

**Task list**
- [ ] **Conceptual extensions**
   - [ ] Check: class TrainingResultsRL inherited from bf.mt.Shared (or maybe better: bf.ml.TrainingResults inherited from Shared)?
- [ ] **Changes on class bf.ml.TrainingResults**
   - [ ] New parent class bf.mt.Shared
- [ ] **Changes on class bf.ml.Training**
   - [ ] New parent class Task (part of #408)
   - [ ] Class TrainingResults als default class for parameter p_class_shared
- [ ] **Changes on class TrainingRL**
   - [ ] Start of evaluation episodes asynchronously (method _run_async) without logging (range multiprocessing only)
   - [ ] Wait for termination
- [ ] **New howto that demonstrates the acceleration on two training runs with/without multitasking**

**Related issues**
#391 #408

**Comment by detlefarend** [comment]
@steveyuwono @rizkydiprasetya interesting for you? Before that we should clearify the underlying multitasking functionalities of #391

**Comment by steveyuwono** [comment]
> @steveyuwono @rizkydiprasetya interesting for you? Before that we should clearify the underlying multitasking functionalities of #391

Yes, this can be a good future improvement and speed up the evaluation process, but maybe not be the highest priority at the moment. To be honest, I very rarely activate the evaluation functionality.

**Comment by rizkydiprasetya** [comment]
I dont see any significant benefit on doing evaluation asynchronously. And yes, we barely use evaluation in RL. One commonly used is parallel training. By parallel training, for sure, we can accelerate the training.

**Comment by detlefarend** [comment]
@steveyuwono @rizkydiprasetya No problem. I'll take over at the right time because I see a benefit of speeding up the evaluation by nearly the number of cores times. Parallel training episodes are not in scope of this issue and for sure slightly harder to design/implement.  If you like you could let me know the reasons why you don't use evaluation/stagnation detection. But this discussion is also not in scope of this issue.
