### ISSUE TITLE
RTD: Refactoring API Reference

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#439]
**Description/Motivation**
Appendix 2 for the API Reference needs to be more intuitive and easier to use. Furthermore, all sub-packages and modules need to be preferable.

**Task list**
- [x] 1. Refactoring of the menu structure
- [x] 2. Clear referencing
- [x] 3. Class Diagrams in 200%
- [x] 3. Review due to completeness and correctness

**Comment by detlefarend** [comment]
Hi @steveyuwono @rizkydiprasetya @laxmikantbaheti, to improve the quality of our class diagram images, please export them to png format in the future with a zoom factor of 200%. Thanks!



![Image](https://user-images.githubusercontent.com/79243976/218255599-366e4b4f-a756-41a1-918d-afc0c7c62876.png)
