### ISSUE TITLE
BF-MATH: Possibility to udpate parameters of z-transformer with single data element based on running mean and standard deviation

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#444]
The z-transformer should be able to update on instance/data element

**Task list**
- [x] Update the update_parameters method for p_instance
- [x] update the Howto to demonstrate the feature
- [x] update the class diagram

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, here's the branch: bf_math_normalizer_enh
