### ISSUE TITLE
BF-ML: Class MLTask - Event-based adaptation

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#450]
**Description/Motivation**
Both classes shall be extended by an event-based adaptation systematics.

**Task list**
- [x] **Class MLTask**
   - [x] New method adapt_on_event() 
   To be used as an event handler (see class bf.events.EventHandler)
   - [x] New custom method _adapt_on_event(), called by adapt_on_event()
- [x] Update class diagram
