### ISSUE TITLE
RL/GT: Refactoring Howtos

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#457]
**Description/Motivation**
Over the time the number of howto files was growing and the order and structure is hard to understand for external visitors. To this regard, the howtos shall be grouped and renamed - similar to the bf howtos. Furthermore, the unit test mode shall be optimized.

**Task list**
- [x] 1. Senseful grouping
     - Elementary Topics, Agents, Environments, Adaptive Environments, ...
- [x] 2. Senseful renaming 
     - howto.rl.[num], howto.rl.ag[num], howto.rl.en.[num], howto.rl.ae.[num], ...
- [x] 3. Howtos, global module docstring: additional passage "You will learn"
     See howto.bf.mt.001 as an example.
- [x] 4. Optimizing the dark (non-main) mode: speedup, no outputs/windows/...
     For unit testing it is enough to trigger the related functionalities once or twice.
- [x] 5. Update RTD documentation
- [x] 6. Check/change/complete unit test module

**Related issues**
#455 

**Branch**
rl_gt_howto_fixes

**Comment by steveyuwono** [comment]
Hi @detlefarend, I can take over this part. But maybe after this week, because I have a PK workshop followed by meetings tomorrow and on Friday. Is it fine?

**Comment by detlefarend** [comment]
> Hi @detlefarend, I can take over this part. But maybe after this week, because I have a PK workshop followed by meetings tomorrow and on Friday. Is it fine?

Hi @steveyuwono, very fine! Thank you!

**Comment by detlefarend** [comment]
Hi Steve, could you please prepare a howto group 'Adaptive Environments'? It's for Laxmikant's experiments... Thx!

**Comment by steveyuwono** [comment]
> Hi Steve, could you please prepare a howto group 'Adaptive Environments'? It's for Laxmikant's experiments... Thx!

Sure, I will

**Comment by detlefarend** [comment]
Hi @steveyuwono, just for your information: I added a further group "Advanced Training Techniques" and moved the stagnation detection howtos there...

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, just for your information: I added a further group "Advanced Training Techniques" and moved the stagnation detection howtos there...

Okay perfect, thanks
