### ISSUE TITLE
OA: Howto 001 - Online-normalization of streamed data (Z-Transformation)

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#465]
**Description/Motivation**
This first howto shall demonstrate the basics of stream processing based on a workflow with just the Z-Transformation task within. This workflow shall be combined with a suitable (and well known) data stream from the OpenML project in a custom oa scenario class. 

**Task list**
- [x] **New module howto_oa_pp_001_online_normalization_of_streamed_data_ztrans.py**
   - [x] Own demo scenario class
   - [x] Workflow with Z-Transformer within
   - [ ] Data shall be logged in a local folder (functionality of class OAScenario)
   - [ ] Data of workflow and task shall be visualized (functionality of class OAWorkflow and NormalizerZTrans)
- [ ] **Integration in unit test of MLPro examples**
- [ ] **RTD: Incorporation and description**

**Related issues**
#245 #474 #472 

**Branch**
online_adaptivity6
