### ISSUE TITLE
RL/OA: Double Pendulum - Adaptive extensions

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#466]
**Description/Motivation**
The static versions of double pendulum shall be extended for following versions.

**Task list**
- [x] 1. DoublePendulumOASystems  (OA4, OA7)
- [x] 2. DoublePendulumOAEnvironments (OA4, OA7)
- [x] 3. No extensions at BF-ML level

**Related issues**
#611 

**Cross references**
...
