### ISSUE TITLE
OA: Howto 002 - Online-normalization of streamed data (MinMax)

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#475]
**Description/Motivation**
This howto shall demonstrate the basics of stream processing based on a workflow with a boundary detector and minmax normalizer within. This workflow shall be combined with the data stream used in #465 in a custom oa scenario class. 

**Task list**
- [x] **New module howto_oa_pp_002_online_normalization_of_streamed_data_minmax.py**
   - [x] Own demo scenario class
   - [x] Workflow with boundary detector and minmax normalizer within
   - [ ] Data shall be logged in a local folder (functionality of class OAScenario)
   - [x] Data of workflow and task shall be visualized (functionality of class OAWorkflow both tasks)
- [ ] **Integration in unit test of MLPro examples**
- [ ] **RTD: Incorporation and description**

**Related issues**
#245 #474 #384 #472 #465 

**Branch**
online_adaptivity10

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti I guess this issue is related to the current howto_oa_001_normalizer_minmax.py.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I made the mentioned changes to boundary detector and normalizers.
Are there any other high priority tasks, that I can work today?

**Comment by laxmikantbaheti** [comment]
hi @detlefarend , now the normalizer event handler adapts with this new event, C_EVENT_ADAPTED.
But, since this event is raised at module mt.py level, there is no additional info passed about the instance itself. which we need to update the normalizer parameters. In this case, one possibility is to access the instance from shared object, of the event was raised by boundary detector?
Shall I go ahead like this?

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, the problem is that at the time point of the event the updated instances are not stored in the shared object. How about a new method BoundaryDetector.get_boundaries()?

**Comment by laxmikantbaheti** [comment]
We actually don't need an updated instance in case of adaptation of boundary detector, cause we need to access the related set. As the boundaries are updated there.

**Comment by laxmikantbaheti** [comment]
Okay, yes.

I will implement this with get_related_set() then.
