### ISSUE TITLE
BF-Math: Update parameters on deleted Instances for Z transformer

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#478]
**New method update_parameters_del() that updates the parameters of z-transformer when obsolete data is removed from the dataset (window)**
...

**Task list**
- [x] 1. New method _update_parameters_del()
- [x] 2. rename method _update_parmeters() to _update_parameters_new()
- [x] 3. class diagram and howto modifications

**Task List (Redefined)**
- [x] 1. Method _update_parameters() takes 3 arguments, if prvided p_data_del, then the parameters are updated based on replacement otherwise normally
- [x] 2. update class diagram
- [x] 3. update how to

**Related issues**
#...

**Cross references**
...
