### ISSUE TITLE
BF-Streams: Howtos for Stream-Tasks, -Workflows, -Scenarios

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#483]
**Description/Motivation**
This first howto introduces the basics of stream processing in MLPro based on a workflow with a hierarchy of dummy tasks and data visualization.

**Task list**
- [ ] **New module howto_bf_streams_101_stream_task_scenario.py**
   - [x] Own demo task
   - [x] Workflow with just one demo task
   - [ ] Data shall be logged in a local folder (functionality of class StreamScenario)
   - [ ] Data of  task shall be visualized (functionality of class StreamTask)
- [ ] **New module howto_bf_streams_102_tasks_workflows_and_stream_scenarios.py**
   - [x] Own demo task
   - [x] Workflow with task hierarchy (see also: howto-bf-mt-002)
   - [ ] Data shall be logged in a local folder (functionality of class StreamScenario)
   - [ ] Data of workflow and task shall be visualized (functionality of class StreamTask and StreamWorkflow)
- [ ] **Integration in unit test of MLPro examples**
- [ ] **RTD: Incorporation and description**

**Related issues**
#484 

**Branch**
bf_streams
