### ISSUE TITLE
BF-Streams: New classes StreamTask, StreamWorkflow, StreamScenario

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#484]
**Description/Motivation**
These three classes form the core of stream processing in MLPro.

**Task list**

**1. Concepts**
   - [x] Concept for evolving instances
         - The master workflow instantiates a shared object and inserts the initial instance
         - A stream task processes all instances of it's direct predecessors
         - A stream task inserts it's result instances to the so - even if they are unchanged
   - [x] Concept for performant online-visualization

**2. Design**   
   - [x] Class diagram
 
**3. Implementation** 
   - [x] Class StreamShared
      - [x] Data structure and methods for evolving instances
   - [ ] Class StreamTask
       - [x] Parameter p_duplicate_instances
       - [ ] Default visualization
          - [x] Plot parameter 'step rate'
          - [ ] Plot parameter 'horizon'
          - [x] Default visualization 2D
              - [x] Visualization of new instances
              - [x] Visualization of deleted instances
          - [x] Default visualization 3D
              - [x] Visualization of new instances
              - [x] Visualization of deleted instances 
          - [x] Default visualization nD
              - [x] Visualization of new instances
              - [x] Visualization of deleted instances (Laxmikant)
   - [x] Class StreamWorkflow
       - [x] Visualization 
       - [ ] Auto-arrangement of task windows
   - [x] Class StreamScenario

**Related issues**
#485

**Comment by detlefarend** [comment]
Current problems to solve:

- [ ] Handover of results of a task to successor tasks on event C_EVENT_FINISHED
    Probably by storing them in the shared object...

**Comment by detlefarend** [comment]
Approach after today's meeting (@laxmikantbaheti @detlefarend): shared object with an inner stack

![2022-12-02_10-50](https://user-images.githubusercontent.com/79243976/205265383-ca3e9abb-4e64-41d8-a737-35687a0032f5.png)

**Comment by detlefarend** [comment]
@laxmikantbaheti your improvements of nD visualization look good!

**Comment by detlefarend** [comment]
Some thoughts on auto-arrangement...
![image](https://user-images.githubusercontent.com/79243976/210181445-d3cf8cb6-6293-4ae7-acb1-3779f3a01ce2.jpeg)
