### ISSUE TITLE
BF-OPS: New root class for scenarios

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#485]
**Description/Motivation**
A new module bf.ops shall be added to bf-layer 1 ("Computation"). Classes Mode and Scenario shall be placed there.

**Task list**
- [x] 1. New module bf.ops
- [x] 2. Transfer of class Mode from bf.ml to bf.ops
- [x] 3. New root class Scenario
- [x] 4. RTD: extension of API documentation

**Branch**
bf_ops
