### ISSUE TITLE
BF-ML: Refactoring of method Model.adapt()

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#488]
The interface of method bf.ml.Model.adapt() shall be changed. The current parameters *p_par shall be replaced by **p_kwargs.

**Tasks:**

- [ ] **Change of method bf.ml.Model.adapt()**
- [ ] **Changes in MLPro-RL**
  - [ ] Policy._adapt()
  - [ ] Policy implementations of pool classes
  - [ ] Agent._adapt()
  - [ ] MultiAgent._adapt()
- [ ] **Changes on Wrappers**
  - [ ] SB3 wrapper
