### ISSUE TITLE
Download statistics

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#494]
**Description/Motivation**
Currently we don't know how often MLPro was downloaded from PyPI or Anaconda. Knowing about this is helpful to assess the spread and relevance of the project and to convince interested persons/companies. A counter or graph could even be published on RTD. 

**Task list**
- [x] 1. Evaluation
   - [x] PyPI
   - [x] Anaconda
- [ ] 2. Counter badges on the repo readme
   - [x] Counter for PyPI downloads
   - [ ] Counter for Anaconda downloads
   

**Cross references**

https://pypi.org/project/mlpro/#data

https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/

https://libraries.io/pypi/mlpro

**Comment by rizkydiprasetya** [comment]
I can put the download counter on the Github readme, if you want

**Comment by detlefarend** [comment]
Good idea! Is it easy or hard to create a table like this?

Source    Total   Last month
----------------------------
PyPI      127     18
Anaconda   99     11

Total     226     29

**Comment by rizkydiprasetya** [comment]
check this : https://github.com/fhswf/MLPro/tree/download-stats

**Comment by detlefarend** [comment]
Awesome!! With detail statistics if I click on the badge. Can we do the same for anaconda? It seems that pepy supports pypi only...

**Comment by rizkydiprasetya** [comment]
So far I havent found something like that for anaconda. Only the total downloads count can be shown. As in number not like pepy with graph.

**Comment by detlefarend** [comment]
Fine so far. I guess pypi is and will be the main download source. Could you please also add this functionality to the MLPro-Extension repo? Thank you!

**Comment by rizkydiprasetya** [comment]
Sure, will do.
