### ISSUE TITLE
BF-Streams: StreamTask Rearranger

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#519]
**Description/Motivation**
A new pool class _Rearranger_ shall be implemented. It replaces incoming instances (new/del) by new ones that are modified based on rearrangement rules for features and labels. To this regard, the new feature and label spaces are described by optional list parameters with entries that refer to origin features and labels. This enables in particular
- changing positions of features/labels
- remove features/labels
- use features as labels and vice versa

**Task list**
- [x] **New module bf.streams.tasks.rearranger.py**
- [x] **New class _Rearranger_ (inherited from StreamTask)**
   - [x] Constructor: new optional parameters _p_features_new : list_, _p_labels_new : list_
          Entries are tuples like: 
          - "F"/"L" (origin: feature or label)
          - Id/name (id or name of origin feature/label)
   - [x] Method _init_spaces( p_inst:Instance) -> MSpace, MSpace
         To be used for late initialization of rearranged feature and label space based on the first incoming instance. The base classes for both spaces shall be taken over from the incoming instance.
   - [x] Method _rearrange_data( p_inst_in, p_inst_out )
   - [x] Method _run()
   - [x] Visualization: default
- [x] **Howto to validate/demonstrate the functionalies**
- [ ] **RTD extension**
 

**Related issues**
#484 #546 

**Further hints**
See class diagram.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti , could you please take a look whether the specification is valid and complete? Do you see further possibilites of rearrangement?

**Comment by laxmikantbaheti** [comment]
This looks good.
This will create its own space, right?

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, that's true. I just reworked the spec. I think it's easier to understand and implement if we describe the new feature and label space by lists with entries that refer to existing f/l...

**Comment by detlefarend** [comment]
@laxmikantbaheti I'll take over due to my today's presentation
