### ISSUE TITLE
OA-Task: AnomalyDetector

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#520]
Online anomaly detectors recognize exceptions in data streams. To this regard, a template class shall be elaborated. Furthermore, wrappers for suitable 3rd-party packages shall be implemented and tested.

**ToDo**
- [x] **New module mlpro.oa.tasks.anomalydetector.py**
- [x] **Template class AnomalyDetector**
- [ ] **Wrapper River**
      [River](https://riverml.xyzl) provides a number of algorithms based on a template class "AnomalyDetector". The concepts and implementation details shall be examined and a suitable wrapper class WrAnomalyDetectorRiver shall be implemented. See the API description of the current version for further details (section "anomaly").
- [x] **Wrapper Scikit-learn**
      [Scikit-learn](https://scikit-learn.org/stable/index.html) provides algorithms for outlier and novelty detection based on datasets. Perhaps they can be applied to streams as well (to be examined)...
- [x] **Howtos for all wrappers and algorithms**
    - [x] Howto with workflow and all anomaly detectors as parallel oa-tasks

**Cross references**
https://riverml.xyz
https://scikit-learn.org/stable/index.html
https://scikit-learn.org/stable/modules/outlier_detection.html
MLPro-OA class diagram

**Comment by detlefarend** [comment]
@laxmikantbaheti fyi
