### ISSUE TITLE
BF-Streams: StreamTask Deriver

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#546]
**Description/Motivation**
A new pool class _Deriver_ shall be implemented. It replaces an incoming instance (new/del) by an extended one with further features/labels that are numerically derived from existing ones. The derivation algorithm and horizon shall be adjustable. The use case behind is to add the velocity and acceleration of a feature/label as further features/labels to the feature/label space.

**Task list**
- [x] **New module bf.streams.tasks.deriver.py**
- [x] **New class _Deriver_ (inherited from StreamTask)**
    - [x] Constructor: new parameter _p_deriver_rules : list_
          Entries are tuples like: 
          - "F"/"L" (feature or label)
          - Id/name (id or name of origin feature/label)
          - Degree of derivation (=number of additional features/labels)
          - Algorithm
          - Horizion
          - ...
    - [x] Method _init_spaces( p_inst ) -> MSpace, MSpace  
    - [x] Method _derive_data( p_inst_in, p_inst_out )
- [x] **New howto to validate/demonstrate the functionalities**
- [x] **RTD extension**

**Related issues**
#484 #519 

**Further hints**
See class diagram.

**Comment by detlefarend** [comment]
@laxmikantbaheti and here's the spec for a deriver. I am curious about your estimation.

**Comment by laxmikantbaheti** [comment]
Currently our implementations for acceleration and velocity are based on hard-coded mathematical functions which are Integrated over time using odeint. 
I am not sure, if this should be a deriver or integrator.
I did not find any implementation for directly deriving a feature, so far.

**Comment by laxmikantbaheti** [comment]
Currently our implementations for acceleration and velocity are based on hard-coded mathematical functions which are Integrated over time using odeint. 
I am not sure, if this should be a deriver or integrator.
I did not find any implementation for directly deriving a feature, so far.

**Comment by laxmikantbaheti** [comment]
Yes, that's perfect. Sorry I couldn't frame it correctly in the last message. In our current implementation the derivative functions are hard coded. For velocity over position, acceleration over velocity. And these deriving functions are passed to the numpy odeint function to integrate in reverse order to calculate the corresponding values.
I wanted to emphasize that, currently we have to feed the derivative functions manually.
But I believe, if we have accurate information about the time step, it should be possible to directly calculate a gradient over time.
We shall validate it once. I am positive that it will work. But, because I couldn't find any implementation for real time derivations, in numpy.

**Comment by detlefarend** [comment]
I see. A simple first algo could be like this

![grafik](https://user-images.githubusercontent.com/79243976/203531832-bbceb443-d66e-4f0d-9288-7dab2da06af9.png)

Further algos to be discussed. Maybe a numpy-based (non-)linear regression...

**Comment by laxmikantbaheti** [comment]
Hi, I just checked this by applying on double pendulum. And this definitely works.

**Comment by laxmikantbaheti** [comment]
It failed in the UR5 env, I believe
![image](https://user-images.githubusercontent.com/100450659/203547369-08f00143-8d72-45f1-8471-8f743f9bc24f.png)

**Comment by detlefarend** [comment]
Our workflows are on green again:)

**Comment by steveyuwono** [comment]
Hi @detlefarend and @laxmikantbaheti , I just added a stream task Deriver to our framework with the primary derivative function f′(x) = limΔx→0 (f(x+Δx) − f(x)) /Δx. I also added a howto file (bf streams 114), which I am not sure is necessary because it looks similar to howto for rearranger but with a different stream task.

You can review it and let me know your feedback if you have time. Thank you!

**Comment by detlefarend** [comment]
> Hi @detlefarend and @laxmikantbaheti , I just added a stream task Deriver to our framework with the primary derivative function f′(x) = limΔx→0 (f(x+Δx) − f(x)) /Δx. I also added a howto file (bf streams 114), which I am not sure is necessary because it looks similar to howto for rearranger but with a different stream task.
> 
> You can review it and let me know your feedback if you have time. Thank you!

Hi @steveyuwono, I just took a look at the howto and the code of the Deriver. It looks very good and clean to me. The difficulty with the howto is that it is hard to validate whether the plot results are plausible. In this regard, I suggest some changes. Maybe the native stream doublespiral2d is a better choice. Then a workflow like this: rearranger(2->1), deriver1, deriver2. Due to the automatic view selection, this should lead to four plots, 2D (native stream data), 1D (reduced by the rearranger), 2D (first derivation), and 3D (second derivation). In our case, it would be better to turn off this automatic to get four nD line plots with 2,1,2,3 plot curves. A feature that is not yet implemented but soon...

**Comment by steveyuwono** [comment]
> > Hi @detlefarend and @laxmikantbaheti , I just added a stream task Deriver to our framework with the primary derivative function f′(x) = limΔx→0 (f(x+Δx) − f(x)) /Δx. I also added a howto file (bf streams 114), which I am not sure is necessary because it looks similar to howto for rearranger but with a different stream task.
> > You can review it and let me know your feedback if you have time. Thank you!
> 
> Hi @steveyuwono, I just took a look at the howto and the code of the Deriver. It looks very good and clean to me. The difficulty with the howto is that it is hard to validate whether the plot results are plausible. In this regard, I suggest some changes. Maybe the native stream doublespiral2d is a better choice. Then a workflow like this: rearranger(2->1), deriver1, deriver2. Due to the automatic view selection, this should lead to four plots, 2D (native stream data), 1D (reduced by the rearranger), 2D (first derivation), and 3D (second derivation). In our case, it would be better to turn off this automatic to get four nD line plots with 2,1,2,3 plot curves. A feature that is not yet implemented but soon...

Hi @detlefarend, thank you for your comments and suggestions. I have updated the howto file accordingly and it looks like the calculation is correct. Additionally, I will add the related documentation later to the RTD.

**Comment by detlefarend** [comment]
Hi @steveyuwono, I took a look at the updated howto. It looks exciting and basically as expected. We can interpret it better if all plots are in nD mode. In my following documentation breaks, I will improve the stream plotting features (switch for automatic view selection, auto-arrangement, ...). Maybe we could discuss the improvements together... Yes, I'll put it on the agenda for the next OA slot...

**Comment by laxmikantbaheti** [comment]
Hi @steveyuwono , does the rearranger add the new dimension as the first dimension or the last?
