### ISSUE TITLE
Sprint Planning

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#548]
**Preparation**
- [x] Appointment scheduled? Room booked?
- [x] Attendees informed?

**Agenda**
- [x] **Review/close of current sprint**
- [x] **Planning of next sprint/final release 1**
  - [x] Review of unassigned issues
  - [x] Review/agreement of workload of collaborators
  - [x] New sprint planning issue
- [x] **Special topic #1: RTD - Intro and Basic Functions**
- [x] **Special topic #2: PyPI/Anaconda - Installation variants**
- [x] **Special topic #3: MuJoCo Integration**
- [x] **Check: decisions documented?**
