### ISSUE TITLE
BF-Systems: Introduce TransferFunction Class

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#578]
**Description/Motivation**
Shift TransferFunction Class from mlpro_at_basis to bf.systems

**Task list**
- [ ] Shift TransferFunction Class from mlpro_at_basis to bf.systems
- [ ] Update documentation (class diagram, section 2.1 in RTD, etc.)
- [ ] Howto file and its documentation
- [ ] Function approximation: exclude from the class?

**Related issues**
#...

**Cross references**
...
