### ISSUE TITLE
OA-Task: Templates for Cluster Analyzers

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#589]
**Todo**

- [x] **1. Class ClusterAnalyzer**
    - [x] Implementation of method renormalize()
- [x] **2. Class Cluster**
    - [x] Custom method for renormalization
    - [x] Set of general properties
- [x] **3. Class ClusterCentroid**
    - [x] Implementation of renormalization method

**Related Issues**
#739

**Comment by steveyuwono** [comment]
Hi Detlef, I have updated the other wrapped river algorithms according to the introduction of the _update_clusters() method, as we did for CluStream in the last meeting, as well as the class diagram. However, the howtos for river algorithm validations have failed.

If you remember, at the end of our last meeting, you added related_cluster.init_plot(...), as shown in the screenshot below, because the howto oa ca 002 was showing a wrong visualization, where it opened a new window for each added cluster. But, this makes howto oa we 001-005 have failed because self._figure is not yet defined. Without this line of code, these howtos run properly.

Do you have any ideas about what causes the problem?

![image](https://github.com/fhswf/MLPro/assets/88610818/28528611-2de5-4289-9600-035a5d825469)
![image](https://github.com/fhswf/MLPro/assets/88610818/ec84fdef-1007-45c5-a4c1-25f8c08830a6)

**Comment by detlefarend** [comment]
> Hi Detlef, I have updated the other wrapped river algorithms according to the introduction of the _update_clusters() method, as we did for CluStream in the last meeting, as well as the class diagram. However, the howtos for river algorithm validations have failed.
> 
> If you remember, at the end of our last meeting, you added related_cluster.init_plot(...), as shown in the screenshot below, because the howto oa ca 002 was showing a wrong visualization, where it opened a new window for each added cluster. But, this makes howto oa we 001-005 have failed because self._figure is not yet defined. Without this line of code, these howtos run properly.
> 
> Do you have any ideas about what causes the problem?
> 
> ![image](https://github.com/fhswf/MLPro/assets/88610818/28528611-2de5-4289-9600-035a5d825469)
> ![image](https://github.com/fhswf/MLPro/assets/88610818/ec84fdef-1007-45c5-a4c1-25f8c08830a6)
> 
> 

Hi Steve, I'll analyze and fix it...

**Comment by steveyuwono** [comment]
Btw, regarding howto oa ca 002, I have tested some parameters of the CluStream and at the moment not including the normalization. Some combinations of parameters are getting closer to the desired target, as shown in the picture below. Hence, I believe this is just a matter of hyperparameter tuning

![Figure_1](https://github.com/fhswf/MLPro/assets/88610818/72807a7b-b56d-439f-9859-d90e35ebf24a)

**Comment by detlefarend** [comment]
Hi @steveyuwono, there is a basic challenge with the wrapped River algos combined with MLPro normalization: if the normalizer updates it's internal parameters, all subsequent tasks need to renormalize buffered data like centroids. We can deal with it in three ways:
- Preferred: we update internally buffered data, if possible
- We reset the algo and loose the current learning progress
- We don't use the River algos in combination with our normalizers

All of the options are better than keeping centroids on wrong positions...

Maybe we should enable optional renormalization as a basic function of OA-Tasks... I need to think about this and come back as soon as I have a concept...

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, there is a basic challenge with the wrapped River algos combined with MLPro normalization: if the normalizer updates it's internal parameters, all subsequent tasks need to renormalize buffered data like centroids. We can deal with it in three ways:
> 
> * Preferred: we update internally buffered data, if possible
> * We reset the algo and loose the current learning progress
> * We don't use the River algos in combination with our normalizers
> 
> All of the options are better than keeping centroids on wrong positions...
> 
> Maybe we should enable optional renormalization as a basic function of OA-Tasks... I need to think about this and come back as soon as I have a concept...

I can imagine that resetting the algo every time the normalizer updates its internal parameters is not preferable. If this happens in the middle or almost the end of the data streams, then it would be very dissatisfying to lose the whole learning progress. Imho, solutions 1 and 3 are more suitable.

**Comment by detlefarend** [comment]
> > Hi @steveyuwono, there is a basic challenge with the wrapped River algos combined with MLPro normalization: if the normalizer updates it's internal parameters, all subsequent tasks need to renormalize buffered data like centroids. We can deal with it in three ways:
> > 
> > * Preferred: we update internally buffered data, if possible
> > * We reset the algo and loose the current learning progress
> > * We don't use the River algos in combination with our normalizers
> > 
> > All of the options are better than keeping centroids on wrong positions...
> > Maybe we should enable optional renormalization as a basic function of OA-Tasks... I need to think about this and come back as soon as I have a concept...
> 
> I can imagine that resetting the algo every time the normalizer updates its internal parameters is not preferable. If this happens in the middle or almost the end of the data streams, then it would be very dissatisfying to lose the whole learning progress. Imho, solutions 1 and 3 are more suitable.

I've tackled a general solution for renormalization that allows specific renormalization in a standardized way. I'll implement it tomorrow or on Wednesday. After that I would like to explain/discuss it in a short zoom call. At the end, a new custom method **renormalize()** is to be implemented - either on level cluster analyzer or on level cluster. 
The plot problem is not yet solved. I'll solve this in the next few days as well.

**Comment by steveyuwono** [comment]
> > > Hi @steveyuwono, there is a basic challenge with the wrapped River algos combined with MLPro normalization: if the normalizer updates it's internal parameters, all subsequent tasks need to renormalize buffered data like centroids. We can deal with it in three ways:
> > > 
> > > * Preferred: we update internally buffered data, if possible
> > > * We reset the algo and loose the current learning progress
> > > * We don't use the River algos in combination with our normalizers
> > > 
> > > All of the options are better than keeping centroids on wrong positions...
> > > Maybe we should enable optional renormalization as a basic function of OA-Tasks... I need to think about this and come back as soon as I have a concept...
> > 
> > 
> > I can imagine that resetting the algo every time the normalizer updates its internal parameters is not preferable. If this happens in the middle or almost the end of the data streams, then it would be very dissatisfying to lose the whole learning progress. Imho, solutions 1 and 3 are more suitable.
> 
> I've tackled a general solution for renormalization that allows specific renormalization in a standardized way. I'll implement it tomorrow or on Wednesday. After that I would like to explain/discuss it in a short zoom call. At the end, a new custom method **renormalize()** is to be implemented - either on level cluster analyzer or on level cluster. The plot problem is not yet solved. I'll solve this in the next few days as well.

Okay nice, looking forward to it

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, I've added renormalization functionality to the classes OATask, ClusterAnalyzer, Cluster and ClusterCentroid. I've also extended howto_oa_ca_002_clustream_3d_static accordingly. It doesn't raise exceptions and the behavior looks subjectively better. I think there is still one thing to do in the wrappers: the new method _renormalize() needs to be redefined to carry out two steps:
> 
> 1. Call super-method (that finally renormalizes the centroids of the MLPro clusters
> 2. Renormalize the internal centroids of the River algo by applying method p_normalizer.renormalize()
> 
> Could you please redefine for Wrapper CluStream and check the howto again? If that works so far we can move in with the other howtos/river algos...

Hi @detlefarend , thank you for letting me know. Alright, I will update Wrapper CluStream accordingly, but maybe the earliest on Friday.

**Comment by steveyuwono** [comment]
Hi @detlefarend , I have added the _renormalization functionality in each wrapped algorithm by updating the internal centroids in the River algorithm and also updated the related class diagrams. This seems completely fine for KMeans, StreamKMeans, and DenStream. However, I am not really sure how effective is it for CluStream and DBStream, since both of them have micro clusters, which means that we also need to renormalize the micro clusters as well as probably some related variables.

**Comment by detlefarend** [comment]
> Hi @detlefarend , I have added the _renormalization functionality in each wrapped algorithm by updating the internal centroids in the River algorithm and also updated the related class diagrams. This seems completely fine for KMeans, StreamKMeans, and DenStream. However, I am not really sure how effective is it for CluStream and DBStream, since both of them have micro clusters, which means that we also need to renormalize the micro clusters as well as probably some related variables.

Hi @steveyuwono, sounds good. Maybe we can use our tomorrow's MLPro session to
- identify remaining problems
- identify the best performing algos (copy/paste the static howtos)
- improve the visualization

**Comment by steveyuwono** [comment]
> > Hi @detlefarend , I have added the _renormalization functionality in each wrapped algorithm by updating the internal centroids in the River algorithm and also updated the related class diagrams. This seems completely fine for KMeans, StreamKMeans, and DenStream. However, I am not really sure how effective is it for CluStream and DBStream, since both of them have micro clusters, which means that we also need to renormalize the micro clusters as well as probably some related variables.
> 
> Hi @steveyuwono, sounds good. Maybe we can use our tomorrow's MLPro session to
> 
> * identify remaining problems
> * identify the best performing algos (copy/paste the static howtos)
> * improve the visualization

Okay, agree!
