### ISSUE TITLE
BF-ML-Systems: Adaptive Systems

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#611]
**Design and Implementation of Adaptive Systems**
An adaptive system that adapts it's behavior to historic data/real system ("a subsystem in Multisystem"). 

**Task list**
- [x] 1. #698 
- [x] 2. A new class AdaptiveSystem at mlpro.bf.ml.systems
     - [x] inherits from bf.System and bf.ml.Model
     - [x] New parameters p_ada for system
     - [x] New method _switch_adaptivity(p_ada), switches the adpativity of internal functions
     - [x] New method _adapt that calls the adapt method of all the internal functions through try and except blocks (whether the function is apaptive or not).  

**To be finalised:**
Training is a different aspect, thus following is obsolete
- [ ] Pre-training of AFctStrans
- [ ] Defining the Adaptive Systems:
      - Learns from historic Data
      - Learns from a real counterpart
- [ ] Quality check of the adaptive functions
     - Currently checks the quality and skips adaptation...
     - further strategies for adapt shall be there 

**Related issues**
#...

**Cross references**
...

**Comment by laxmikantbaheti** [comment]
Additionally, I was thinking about two new parameters, on AFctBase:

p_pretrain : boolean
p_pretrain_configuration : a dictionary for all the parameters for the pretraining of the AFct, such as epochs, batch size, etc. In my case a CSV file path, episode size etc.
Then a new method:

pretrain(): that calls one such standard workflow of training an Adaptive function. Which takes data instances, or loads batches from buffered data, or something similar and trains the AFct. This pretrain method works in somewhat similar logic the same as training AFctBase in case of MBRL.
