### ISSUE TITLE
OA-Systems: Online Adaptive Systems

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#612]
**Design and implementation of Online Adaptive Systems**
...

**Task list**
- [x] 1. #698 
- [x] 2. #697 
- [x] 3. #611 
- [x] 4. New Module systems mlpro.oa.systems.py
- [x] 5. New Class OASystem(ASystem)
    - [x] 5.1 New classes OAFct*
    - [x] 5.2 Integration of workflows to the functions and consequently to the system,
    - [ ] (Part of the scenario)5.3 Adaptation mechanism that adapts based on new states
    - [ ] (Part of scenario)5.4 This adaptation is to be handled by a scenario, since it needs a truth system as a reference for adaptation and calibration
    - [ ] (Part of the scenario)5.5 A new custom scenario with a reference system and adaptive system.
        - [ ] The adaptive system adapts just as in MBRL

**Related issues**
#...

**Cross references**
...

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, In our last meeting we talked about online adaptive systems in a special mode: here an env interacts with real hardware and also adapts on it. What do you think of introducing a third mode for it: C_MODE_CLONE or something like that? And if cloning has been finshed (accuracy greater than a threshold) then it raises a special event C_EVENT_SYSTEM_CLONED)...

However, there are some related questions to examine:
- what about evolving systems? Can we do a prediction for their evolution, maybe for a defined horizon?

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, In our last meeting we talked about online adaptive systems in a special mode: here an env interacts with real hardware and also adapts on it. What do you think of introducing a third mode for it: C_MODE_CLONE or something like that? And if cloning has been finshed (accuracy greater than a threshold) then it raises a special event C_EVENT_SYSTEM_CLONED)...
> 
> However, there are some related questions to examine:
> 
> * what about evolving systems? Can we do a prediction for their evolution, maybe for a defined horizon?

Hi @detlefarend , the idea of a new mode is very interesting this will allow us to make changes at lower while maintaining the compatibility. 

I think evolution of a system can be of two types: 
     1. A real system evolves, and our OA system continuously monitors the system ( maybe at some intervals), and adapts to the real system whenever there is an evolution in the system.
     2. Our OA system learns the evolution patterns of real system and then predicts evolutions at time intervals. But I think in this case it is no longer an online adaptive system.

**Comment by detlefarend** [comment]
Remaining tasks are to be done in an extra issue...

**Comment by detlefarend** [comment]
@laxmikantbaheti Hey ho, is there still something to do in **this** issue?
