### ISSUE TITLE
Wrapper: Replace wrapper for Gym by Gymnasium

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#623]
**Description/Motivation**
OpenAI has stopped developing Gym. The Farama Foundation took over and forked the successor called Gymnasium.

**Task list**
- [ ] 1. Implementation of new wrapper for gymnasium
- [ ] 2. Update/validation of all related howtos, in particular in combination with stable_baselines3
- [ ] 3. Remove obsolete wrapper for gym
- [ ] 4. Replace all dependencies to gym by gymnasium (setup.cfg, ...)
- [ ] 5. bf.plot.py: remove restriction for macOS (see changes of 2.8.1 and in the import section)

**Related issues**
#...

**Cross references**
[Gymnasium](https://gymnasium.farama.org/)
https://farama.org/Announcing-The-Farama-Foundation

**Comment by detlefarend** [comment]
@rizkydiprasetya @steveyuwono @laxmikantbaheti fyi... future work.

**Comment by detlefarend** [comment]
The new wrapper for Gymnasium was added. The support for OpenAI Gym is stopped as soon as stable baselines 3 removed its dependency to it. See also: #734
