### ISSUE TITLE
BF-Systems: Scenario class for Systems demonstration

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#627]
**Description/Motivation**
An own senario class is needed to validate and demonstrate the behavior of state-based systems.

**Task list**
- [x] **1. New class bf.systems.DemoScenario**
    - [x] Parent class bf.ops.ScenarioBase
    - [x] Mandatory parameter p_system : System
    - [x] Optional parameter p_action_pattern : str = 'random'
    - [x] Optional parameter p_action : list
    - [x] Further parameters taken over from parent class
    - [x] Method _get_next_action() generates next action depending on action pattern
    - [x] Action patterns: 'random', 'constant'
    - [x] Action pattern 'constant': parameter p_action is taken over
    - [x] Method _run_cycle, that calls the _generate_action method.
- [x] **2. New howto_bf_system_001_validate_native_systems**
    - [x] imports all native systems
    - [x] loops at all native systems
    - [x] runs 10 cycles with random actions w/o visualization
- [x] **3. Check/update/renumbering(>=010) of existing howto_bf_systems_***
- [x] **4. RTD update**

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, is this really done?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I think we decided to discard this issue.

**Comment by detlefarend** [comment]
Didn't we agree for a dummy scenario with random action generator? I think we need something to validate and demonstrate a system on this level. Maybe a Scenario class that supports some action patterns: random, constant zero vector, constant non-zero vector, ...

**Comment by laxmikantbaheti** [comment]
I think, we decided to use the random agent directly in the howtos, or creating dummy scenarios in the howtos. Like it is currently in one of the howtos for systems...

**Comment by detlefarend** [comment]
Probably a misunderstanding. I think, we should provide a standard functionality to validate/demonstrate (multi)systems. Shall I specify something?

**Comment by laxmikantbaheti** [comment]
Okay, sure.
Thank you.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, could you please check/complete/improve the spec? Thx!

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , thanks for elaborating the Demo scenario class.

**Comment by detlefarend** [comment]
> hi @detlefarend , sorry, I sum up again here:
> 
>     1. A custom method _run_cycle, takes state from the _system. generates action from the _generate_next_action method, processes the action in the system and sets teh environment to the new state.
> 
>     2. **Obsolete** (Redefining the _setup method to return State Space and Action space, just like reinforcement learning. Need action space to generate the action.)
> 
>     3. Instead, I setup the spaces in the reset method.
> 
>     4. A reset method, that resets/initializes the system state.

Hi @laxmikantbaheti, I think it's even easier: in _run_cycle: 
- first time: get action space from system
- then: generate action -> state transition
