### ISSUE TITLE
BF-ML: Class Training - Load/save entire scenario

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#630]
The abstract training class shall store the scenario after training.

**Tasks**
- [x] Extensions/changes on class bf.ml.Training
- [x] Demonstration in howto_rl_agent_005_train_and_reload_single_agent.py
- [x] Update of related class diagram (new method get_training_path())
- [x] Validation in all howtos with training part

**Related issues**
#324

**Comment by detlefarend** [comment]
Current problem:

The scenario is now saved as well, but the file is much smaller than the model file:

![2023-02-18_19-09](https://user-images.githubusercontent.com/79243976/219881694-ef907231-9b68-4948-b056-7c690150a85a.png)

Reload of scenario fails in consequence:

![2023-02-18_19-08](https://user-images.githubusercontent.com/79243976/219881599-dc22a21d-3c66-46af-851a-8c8432fb5668.png)

**Comment by detlefarend** [comment]
Next finding: pygame.Surface cannot be pickled:-(

![Image](https://user-images.githubusercontent.com/79243976/219938859-a18e0dbe-c0dd-4f32-8546-9a9602640bbc.png)

**Comment by detlefarend** [comment]
@rizkydiprasetya We have a challange with pickle/dill in combination with pygame: pygame.Surface can't be pickled. That means: there are things that can't be pickled and we need to deal with this (I have already an idea for it). However, could you prepare a cartpole based on mujoco and a howto that trains it? We need to now, whether mujoco-based envs can be pickled...

**Comment by rizkydiprasetya** [comment]
There is one already for double pendulum, you can try that. Whats the different.

**Comment by detlefarend** [comment]
The difference is that we can solve the cart pole but not yet the dp. Anyhow, you are right. I can try to pickle a mujoco env by myself and come back with the result.

**Comment by detlefarend** [comment]
Hi @steveyuwono @rizkydiprasetya @laxmikantbaheti, class bf.ml.Training (and child classes like RLTraining) store the entire scenario now. The persistent version of a scenario is now a subfolder "scenario" with three files inside:
- model 
- environment
- scenario (pickled scenario class without model and env)

The wrapper for Gym envs was extended to avoid the pickle problem caused by Pygame (#635). 

A slightly simplified version of howto_rl_agent_005_train_and_reload_single_agent.py demonstrates the new persistence concept...
