### ISSUE TITLE
SL: Add Ready-to-Use Networks in Pool of Objects

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#634]
**Description/Motivation**
- Add some ready-to-use networks (optionally using PyTorch), e.g. MLP, RNN, LSTM, GRU, and Transformer
- Clean hyperparameters definition
- Update SLAdaptiveFunction because it has not been updated alongside the latest system
- Consider the input-output pairs during adaptation and store them in a buffer, which can be ONLINE or OFFLINE learning. Offline learnig when there is no input-ouput pairs
- See onnx.ai, whether it is possible Wrapper #435 

**Task list**
- [ ] Update SLAdaptive Function
- [ ] Remove OAFunction in MLPro-OA
- [ ] Provide ready-to-use networks in the pool
- [ ] Use them in MBRL (see envmodels pool for robothtm and gridworld)
- [ ] Howto, if necessary
- [ ] RTD documentation

**Related issues**
#435 #232 

**Cross references**
....

**Comment by detlefarend** [comment]
Hi @steveyuwono, what do you think of giving the adaptation of class SLAdaptiveFunction further structure?

adapt() calls _adapt()

_adapt() is currently the custom method

What if _adapt() determines whether the incoming parameters are a dataset (offline SL) or input/output pair (online SL) and calls one of two new custom methods

_adapt_online( p_input:Element, p_output:Element) -> bool
_adapt_offline( p_dataset )

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, what do you think of giving the adaptation of class SLAdaptiveFunction further structure?
> 
> adapt() calls _adapt()
> 
> _adapt() is currently the custom method
> 
> What if _adapt() determines whether the incoming parameters are a dataset (offline SL) or input/output pair (online SL) and calls one of two new custom methods
> 
> _adapt_online( p_input:Element, p_output:Element) -> bool _adapt_offline( p_dataset )

Hi @detlefarend , this is also my concern. At the moment, I am setting up the adapt method with the online learning procedure. For offline learning, initially, I was thinking to fill a buffer (in SLAdaptiveFunction) from a data set, while setting up SLScenario. Then, during adaptation, p_input and p_output can be set up to Nones. However, I prefer with your solution, where we split the adaptation between online and offline. I think I will consider this and propose a design at Friday's meeting.
