### ISSUE TITLE
BF-Streams: Stream sampler

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#643]
**Description/Motivation**
As discussed in #620, a new systematics for sampling sequential stream data shall be added.

![2023-02-23_10-36](https://user-images.githubusercontent.com/79243976/220870024-84322af2-4172-4692-bf37-6c491e8bb303.png)

**Task list**
- [ ] 1. New base class bf.streams.Sampler
- [ ] 2. New pool bf.streams.sampler for stream samplers
- [ ] 3. First implementation bf.streams.SamplerRND for sampling instances based on a random step rate
- [ ] 4. New method Stream.set_sampler( p_samper : Sampler )
- [ ] 5. Suitable howto(s)

**Related issues**
#620

**Cross references**
...

**Comment by detlefarend** [comment]
Hi @steveyuwono, could you please take over this issue?

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, could you please take over this issue?

Sure, I can take over this issue
