### ISSUE TITLE
BF/RL: MuJoCo-based CartPole system

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#648]
**Description/Motivation**
Here are some proposals for improvements/simplifications of the presentation of our MuJoCo integration.

**Task list**
- [x] **1. Howto BF Systems 003: simplification**
       I think we don't need a special class CartPoleSystem. We can use the class System directly.
           
- [x] **2. MuJoCo file - some ideas for improvement**
       I'd like to assign the visualization of the cart pole and double pendulum. Let's provide a clear and straightforward visualization that is easy to recognize and understand. The squared mirroring floor of the cart pole is a bit confusing. What do you think of adding ax lines for the x,y, and z directions and our MLPro logo somewhere in the background? 
Is it possible to include XML files? If yes, we could prepare a standard "room" for our envs with axes, MLPro logo, ...
          
- [x] **3. Further howtos**
     - [x] 3.1 Howto for continuous cart pole
     - [x] 3.2 Howto for discrete cart pole and stagnation detection
     - [x] 3.3 Howto for continuous cart pole and stagnation detection
