### ISSUE TITLE
Review/redesign of persistence strategy

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#664]
**Description/Motivation**
Currently, **howto_rl_mb_001_train_and_reload_model_based_agent_gym.py** fails due to problem pickling the PyTorch-based class "PyTorchMLP". That points out a general problem by pickling macro-objects like model based multi-agents...

The recommended approach is to ise and extend the custom functionalies of pickle to enable individual persistence of data elements/objects that can not be pickled.

**Task list**
- [x] **0. Evaluation**
    - [x] Possibilites of adding [custom extensions of pickle](https://docs.python.org/3/library/pickle.html#persistence-of-external-objects)
- [x] **1. New class Persistent** 
    - [x] replaces classes Load, Save, LoadSave
    - [x] logging
    - [x] howto_bf_005_persistence.py
    - [x] path-problem: it shall be possible to load objects from differing paths - even in multithreading
       Approach: global dictionary that stores the path for a given filename...
    - [x] Versioning
          The implementation version shall be raised on incompatible changes to log/deny incompatible files
    - [x] Update of related class diagrams
- [x] **2. Refactoring of existing redefinitions**
    - [x] bf.ops.ScenarioBase
    - [x] bf.streams.StreamScenario
    - [x] bf.ml.Model
    - [x] bf.ml.Scenario
    - [x] bf.ml.TrainingResults
    - [x] Wrappers 
        - [x] gym
        - [x] pettingzoo
    - [x] bf.systems.System
- [x] **3. Further candidates for redefinition**
    - bf.mt.Task, bf.mt.Workflow ( #674 )
    - [x] rl.Policy
    - [x] rl.Agent
    - [x] rl.MultiAgent
    - [x] rl.EnvModel
    - [x] rl.RLScenario
- [x] **4. RTD**
    - [x] Section MLPro-BF: Explanations of MLPro's persistence strategy
    - [x] Class diagrams 
        - [x] bf.systems
        - [x] bf.ml

**Cross references**
https://pytorch.org/tutorials/beginner/saving_loading_models.html
https://stackoverflow.com/questions/62090674/pytorch-model-saving-error-cant-pickle-local-object
https://docs.python.org/3/library/pickle.html#persistence-of-external-objects
