### ISSUE TITLE
BF-Systems: Design for Hierarchical Systems

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#671]
**Description/Motivation**
   Extension of Systems class for complex systems (Cascaded, , Parallel, Hierarchical, etc.)  with possibilities to add tasks with dependencies.
![image](https://user-images.githubusercontent.com/100450659/225918735-5d8a8bcb-c1d9-4094-9203-51365349fe09.png)
![image](https://user-images.githubusercontent.com/100450659/225918781-9bcf9f40-6a82-410d-90d8-741c13a37fea.png)

**Task list**
- [ ] **1. Updates on the System Class:**
    - [ ] Inherits from Task
    - [ ] New optional parameter p_t_step, this attribute shall be passed in the simulate reaction method
    - [ ] New method _run() that calls the simulate reaction method
    - [ ] More updates as shown in the class diagrams for methods for getting functions
   
- [ ] **1. New class bf.systems.MultiSystem (or ComplexSystem)**
    - [ ] Parent classes: bf.systems.System, bf.mt.Workflow
    - [ ] New Method add_system()
         ... calls internally the method add_task()
    - [ ] Method **_simulate_reaction()**: complex parallel/aysnchronous simulation of systems within
           The simulate reaction of the multisystem simulates each of the subsystems by an amount equal to t_step in each cycle. This t_step is the smallest latency of all the subsystems inside
   -  [ ] Method **setup()**, sets up a new state ("MultiState") that is a set of all the states and action spaces of all the sub-systems within. Subsequently each subsystems fetches it's interesting state/action by mapping over the mult-state
   - [ ] New method **run()**, runs all the run methods on the subsystem tasks, which consequently calls the simulate reaction method of the subsystems.
- [ ] **2. Suitable Howtos**
- [ ] **3. Updates on RTD**
    - [ ] Documentation bf.systems
    - [ ] Class diagram bf.systems

**Related issues**
#664 #672 #396

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I concretized the issue based on our last discussion. I propose to avoid the term "complex" due to two reasons: 
- the association to complex numbers
- "multi" is more MLPro style (MultiAgent, MultiPlayer)

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, I concretized the issue based on our last discussion. I propose to avoid the term "complex" due to two reasons: 
> - the association with complex numbers
> - "multi" is more MLPro style (MultiAgent, MultiPlayer)

Hi @detlefarend , thanks for making it more concrete. 
I agree with you. "Multi" brings it to a more lower level term.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti , I just took a look at the class diagram. It is a clean design! Here are some annotations from my side:
- **Class System: _id, set_id()**
  During my last refactoring of persistence, I introduced a new class **Id**, that adds everything around a unique Id (attribute, methods) to a child class. Since **Task** is persistent, it inherits from Persistent that, in turn, inherits from Id. Long story short: you don't need to care for it - except in the constructor (as you already did).
- **Multi-States**
   In bf.ml, we introduced the HyperParamDispatcher that behaves like a HyperParamTuple but references to HPs of models you can add by calling method add_hp_tuple(). We could provide something like that on a lower level (bf.math) for spaces. That makes it easier to deal with multiple states, actions, ... on higher levels. Eventually, it could replace class MultiState...
   However, to support multitasking, placing it in a shared object is a good idea. 
- **Class MultiSystem**
   - Method _simulate_reaction() is not optional and is to be implemented. (non-trivial as discussed)
   - Methods for plotting: are also not custom at this level. They need to trigger the related methods of the embedded systems or deal with a Multi-Mujoco-file, on the other hand...
- **Copy/Paste errors**
   - In class MultiSystem, the method compute_success() is there twice. One of them should be compute_broken().
   - Class SystemShared, first and second yellow boxes on the right are identical
 
Hope that helps...
