### ISSUE TITLE
BF: Persistence of classes Task, Workflow

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#674]
**Description/Motivation**
Persistence shall be added to the classes bf.mt.Task and bf.mt.Workflow.

**Task list**
- [x] **1. Persistence of class Task**
   - [x] New parent class bf.various.Persistent
   - [x] Review of persistence of all child classes
- [ ] **2. Updates on RTD**
   - [x] Class diagram bf.mt
   - [ ] Descriptions of MLPro-BF

**Related issues**
#664
