### ISSUE TITLE
Sprint Planning 2023/04

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#682]
**Preparation**
- [x] Appointment scheduled? Room booked?
- [x] Attendees informed?

**Agenda**
- [x] **Review/close of current sprint**
- [x] **Planning of next sprint**
  - [x] Review of unassigned issues
  - [x] Review/agreement of workload of collaborators
  - [x] New sprint planning issue
- [ ] **Special topic #1: Persistence** (Detlef)
- [ ] **Special topic #2: Release Notes** (Detlef)
- [ ] **Special topic #3: MultiSystems** (Laxmikant)
- [ ] **Check: decisions documented?**
