### ISSUE TITLE
RTD-OA: Activation and initial structure

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#704]
**Description/Motivation**
...

**Task list**
- [x] 1. Start page: activation and repositioning of the tile for sub-framework MLPro-OA
- [x] 2. Section Order: MLPro-SL, MLPro-OA, ...
- [x] 3. Section MLPro-OA: initial sub-structure
- [x] 4. Update of architecture image
