### ISSUE TITLE
RTD-BF-Streams: Subsection for 3rd-party support 

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#719]
**Description/Motivation**

**Task list**
- [ ] **Subsection "3.5.1.4 3rd-party Support"
    - [ ] Wrapper for River
    - [ ] Wrapper for Scikit-learn
    - [ ] Wrapper for OpenML

**Comment by detlefarend** [comment]
@laxmikantbaheti Hey ho, we obviously forgot to describe the wrappers. Could you please take over this?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , sure I can do this. Do we have a branch for this?

**Comment by detlefarend** [comment]
> Hi @detlefarend , sure I can do this. Do we have a branch for this? 

Great, thank you! Please create a new branch for it.
