### ISSUE TITLE
WR: Wrapper River 2.0.0

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#735]
**Description/Motivation**
In preparation of upcoming extensions for cluster analysis and anomaly detection the systematics of this wrapper collection shall be reviewed and improved. In particular, a new wrapper base class shall centralize the validation of the installed river version.

**Task list**
- [x] **1. New base class WrapperRiver**
- [x] **2. Review/refactoring of existing wrapper classes**
- [ ] **3. Class diagram**
- [ ] **4. Updates on RTD**

**Comment by detlefarend** [comment]
@laxmikantbaheti @syam47: fyi

**Comment by steveyuwono** [comment]
Hi @detlefarend , could you review the cluster analyzer, its wrappers, and also its how-to?

Here are the related changes that I made:
- https://github.com/fhswf/MLPro/blob/oa/initial_design/src/mlpro/wrappers/river/clusteranalyzers.py
- https://github.com/fhswf/MLPro/blob/oa/initial_design/doc/rtd/content/04_appendices/appendix2/sub/wrappers/images/MLPro-Wrappers-River.drawio.png
- https://github.com/fhswf/MLPro/blob/oa/initial_design/src/mlpro/oa/examples/howto_oa_pp_009_clusteranalyzer_river.py

There are two annotations regarding the cluster analyzers. At the moment, the visualization does not describe the clusters correctly. Is it still under development or should I create an issue for this? Secondly, the cluster analyzer is part of the OA tasks. However, it does not actually affect anything for the feature and label data, other than optimizing the cluster. Is this behaviour fine?

To be noted, the docstring and rtd have not been done yet. I will do this after finalizing this implementation.

Thank you!

**Comment by steveyuwono** [comment]
Hi @detlefarend , thank you for your reply. About the set value of the centroid, I will make sure to update the code accordingly.

Also one more question, in the _run method of the cluster analyzers, the main task is only to update the clusters according to the incoming instances without affecting the data in the instances at all. Thus, the instances before and after passing the cluster analyzing task are no different. I am also calling the get_cluster_membership in this method, which actually has no use in getting the cluster membership in this method. My questions are (1) when actually do we call the get_cluster_membership() or get_clusters() methods? (2) is the current _run method correct?

**Comment by detlefarend** [comment]
> Hi @detlefarend , thank you for your reply. About the set value of the centroid, I will make sure to update the code accordingly.
> 
> Also one more question, in the _run method of the cluster analyzers, the main task is only to update the clusters according to the incoming instances without affecting the data in the instances at all. Thus, the instances before and after passing the cluster analyzing task are no different. I am also calling the get_cluster_membership in this method, which actually has no use in getting the cluster membership in this method. My questions are (1) when actually do we call the get_cluster_membership() or get_clusters() methods? (2) is the current _run method correct?

Hi @steveyuwono, 

regarding _run method of the cluster analyzer. True, the only task during main processing is to update the clusters while keeping the instances untouched. Methods get_clusters and get_cluster_membership are services functions for higher applications. Example could be an anomaly detector based on clusters. 

hth

**Comment by steveyuwono** [comment]
> > Hi @detlefarend , thank you for your reply. About the set value of the centroid, I will make sure to update the code accordingly.
> > Also one more question, in the _run method of the cluster analyzers, the main task is only to update the clusters according to the incoming instances without affecting the data in the instances at all. Thus, the instances before and after passing the cluster analyzing task are no different. I am also calling the get_cluster_membership in this method, which actually has no use in getting the cluster membership in this method. My questions are (1) when actually do we call the get_cluster_membership() or get_clusters() methods? (2) is the current _run method correct?
> 
> Hi @steveyuwono,
> 
> regarding _run method of the cluster analyzer. True, the only task during main processing is to update the clusters while keeping the instances untouched. Methods get_clusters and get_cluster_membership are services functions for higher applications. Example could be an anomaly detector based on clusters.
> 
> hth

Okay understood! Thank you

**Comment by detlefarend** [comment]
Hi @steveyuwono, today I changed some things in class ClusterAnalyzer with an impact to the related wrapper class WrClusterAnalyzerRiver2MLPro:

- I renamed method get_cluster_membership() to get_cluster_membership**s**()
- I added a parameter p_scope, that controls the scope of the result list. There are three possibilities:
     - C_MS_SCOPE_ALL : int = 0
       Membership scope, that includes all clusters
     - C_MS_SCOPE_NONZERO : int = 1
        Membership scope, that includes just clusters with membership values > 0
    - C_MS_SCOPE_MAX : int = 2
        Membership scope, that includes just the cluster with the highest membership value.

I already renamed the method in the wrapper. Could you please extend your implementation of method WrClusterAnalyzerRiver2MLPro.get_cluster_memberships() accordingly?

Then, a second topic: could you please please implement method _adapt() instead of _run() in class WrClusterAnalyzerRiver2MLPro? Method _run() is already implemented in the parent method by just calling adapt(). The code remains the same, but please check whether it is necessary to call method self.get_cluster_memberships() at the end.

Thank you very much!

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, today I changed some things in class ClusterAnalyzer with an impact to the related wrapper class WrClusterAnalyzerRiver2MLPro:
> 
> * I renamed method get_cluster_membership() to get_cluster_membership**s**()
> * I added a parameter p_scope, that controls the scope of the result list. There are three possibilities:
>   
>   * C_MS_SCOPE_ALL : int = 0
>     Membership scope, that includes all clusters
>   * C_MS_SCOPE_NONZERO : int = 1
>     Membership scope, that includes just clusters with membership values > 0
>   * C_MS_SCOPE_MAX : int = 2
>     Membership scope, that includes just the cluster with the highest membership value.
> 
> I already renamed the method in the wrapper. Could you please extend your implementation of method WrClusterAnalyzerRiver2MLPro.get_cluster_memberships() accordingly?
> 
> Then, a second topic: could you please please implement method _adapt() instead of _run() in class WrClusterAnalyzerRiver2MLPro? Method _run() is already implemented in the parent method by just calling adapt(). The code remains the same, but please check whether it is necessary to call method self.get_cluster_memberships() at the end.
> 
> Thank you very much!

Hi @detlefarend , thank you for your review and reply. I will update these accordingly and also add howtos for each algo.
