### ISSUE TITLE
ADMIN: Review/refactoring of CI scripts

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#738]
**Description/Motivation**
Reduction of workflow runtimes, elimination of error sources (OpenML, ...), update of python and package versions, ...

**Task list**
- [x] **1. Optimization of script ci.yml**
    - [x] Job ubuntu_test 
          - Python Versions 3.8, 3,9, 3.10, 3.11
          -  Elimination of package OpenML
          -  Update package river to 0.15.0
    - [x] Job windows_test
          -  Python Version 3.11 only
          -  Elimination of package OpenML
          -  New package MuJoco
          -  Update package river to 0.15.0
    - [x] Job macos_test
          -  Python Version 3.11only
          -  Elimination of package OpenML
          -  New package MuJoco
          -  Update package river to 0.15.0
- [ ]  **2. Optimization of script doc_gen.yml** (DISABLED)
    - [ ] Python version 3.11
    - [ ] Elimination of package OpenML
    - [ ] Update package river to 0.15.0
- [x] **3. File requirements.txt**
    - [x] Update package river to 0.15.0

**Comment by rizkydiprasetya** [comment]
Doc gen is disabled.
