### ISSUE TITLE
BF-MATH: New sub-topic for geometric objects

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#739]
**Description/Motivation**
...

**Task list**
- [x] 1. New module bf.math.geometry.py
- [x] 2. New class Point
- [x] 3. Howto for Point
    - [x] howto_bf_math_020_geometry_point_2d.py
    - [x] howto_bf_math_021_geometry_point_3d.py
