### ISSUE TITLE
BF-Streams: New parameter for velocity in Native Dynamic Cloud 2d and 3d

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#749]
**Description/Motivation**
The current implementations of Native Streams for Dynamic point clouds, calculate the initial centers (in all the cases) of Clouds randomly and final centers based on the specific pattern, which are then divided into 250 (or corresponding) number of points in order to get a moving cloud from first centers to the last centers. 

For a predefined velocity ( units per step ) to be incorporated in the stream, one way is to calculate the centers of the clouds based on the desired velocity. Below is the proposed approach:

**Task list**
- [x] 1. Remove the global step for creating initial centers of all the stream patterns and create one method for each of the pattern as following.

- [x] 2. For random:
    - [x] The initial centers can still be calculated randomly
    - [x] Select also the direction (`theta`) for each instance also randomly
    - [x] Based on the velocity ( `X units/step` ) calculate the final centers as following:
        - The points shall be equidistant from each other at a distance `X` units
        - Calculate the final distance, or total distance: (velocity * steps)
        - To calculate the coordinates of a point (final center) based on distance and angle you can use:
               - x = `X cos theta`
               - y = `X sin theta`
        - Then you can calculate all 250 points like the way you do it currently.
        
- [x] 3. For random chain:
    - [x] In this case, there must be one constraint, only the velocities of 3 clouds can be independent, the 4th is a dependent variable on the former 3
    - [x] The first initial center shall be selected randomly and the next three centers shall be selected based on the velocity of the previous cloud respectively. (Also please select the angle randomly just as the case in previous type)
    - [x] Then the final centers shall be selected just like the current implementation in the branch.
    
- [x] 4. For Merge: I haven't particularly thought about it, but I assume it shall be feasible and very similar

- [x] 5. Once you have the first and final centers, you can proceed with the same approach that you have currently, for calculating the intermediate centers.
- [x] 6. For 3D stream ,the implementation shall be similar, except the direction shall be calculated in 2 planes and also co-ordinates for x, y, z can be calculated, shall be similar.

That shall work. Let me know, if you need further support.

**Related issues**
#...

**Cross references**
...

**Comment by laxmikantbaheti** [comment]
Hi @syam47 , @detlefarend : fyi.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , @syam47 : sorry if you already read it, there's a small update.

**Comment by syam47** [comment]
Updated the code to include the velocity parameter. Please review..
