### ISSUE TITLE
OA-Streams: Anomaly Prediction - Approach #1

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#750]
**Description/Motivation**
Anomaly prediction can be used to predict an anomaly before it occures. One of the applications is predictive maintenance.

One approach to solve this problem is to combine our standard for anomaly detection in combination with a new type of tasks called 'instance predictor'. The latter one generates _n_ imaginary future instances and forwards these as a list to the subsequent anomaly detector. It actually implements a mapping like

_i(t) -> ( i(t), i(t+1), i(t+2),..., i(t+n-1) )_ 

while the first entry is always the current _real_ instance _i(t)_. The anomaly detector needs to turn off it's own adaptation before processing the imaginary instances _( i(t+1), i(t+2),..., i(t+n-1) )_ to avoid adaptation on pseudo data.

**Task list**
- [ ] 1. New base class InstancePredictor (OATask)
- [ ] 2. Extensions on base class OATask
    - [ ] New optional parameter p_adaptation_mode (all instances, first one only)
- [ ] 3. Extensions on base class Model
    - [ ] New method _backup()_
           This method creates an internal backup of all model parameters.
    - [ ] New method _restore()_
           This method restores all model parameters from the last backup

**See also**
#886 
#885

**Comment by detlefarend** [comment]
Today we ( @steveyuwono, @syamrajsatheesh ) discussed an approach based on our (slightly extended) standard for anomaly detection combined with a new type of task called 'instance predictor'...



![Image](https://github.com/fhswf/MLPro/assets/79243976/be277daa-19c8-42b1-998f-d196a56478ae)
