### ISSUE TITLE
GT-Native: Add games to the pool

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#758]
**Description/Motivation**
Add some simple games to the pool of objects:
- [ ] Prisoner's dilemma with 2 players
- [ ] Prisoner's dilemma with 3 players
- [ ] Rock paper scissors
- [ ] Matching pennies
- [ ] something for cooperative games?? Robotic Arms' dilemma??
- [ ] something for competitive games with coalition?? 
- [ ] ......

**Task list**
- [ ] 1. Do this
- [ ] 2. Do that

**Related issues**
#613 #757

**Cross references**
...
