### ISSUE TITLE
GT: RTD Documentation

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#762]
**Description/Motivation**
...

**Task list**
- [x] Split GT-DP and GT-Native in section 7
- [x] Appendices 2 - Pool of solvers and gameboards
- [x] update description routingprblems_3p.py accordingly
- [x] Congestion games howto
- [x] Docstring in all of the base classes
- [x] Check class diagrams
- [x] Check examples
- [x] Check API reference
- [x] API reference basics
  .. automodule:: mlpro.gt.native.basics
     :members:
     :undoc-members:
     :private-members:
     :show-inheritance:
- [x] Remove GT-related automodule / docstring #851 
- [x] Move the howtos file to new directory #864
- [x] Propose MLPro-GT Paper? Conference paper or short journal paper?
- [x] Read me, MLPro github homepage

**Related issues**
#...

**Cross references**
...
