### ISSUE TITLE
WR: Wrapper Scikit-learn 2.0.0

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#768]
**Description/Motivation**
...

**Task list**
- [x] 1. Make the wrapper a sub-package with same name
- [x] 2. Root class for Scikit-learn wrappers (like the River root class)
- [x] 3. Root class for Scikit-learn anomaly detectors (like the related River root class)

**Related issues**
#...

**Cross references**
...
