### ISSUE TITLE
GT-Native: Enhancement of GTStrategy

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#774]
**Description/Motivation**
- The strategy space of each coalition is the probability of choosing each strategy, e.g. 3 possible strategy, then the output of strategy for each player is 3 dimensional, [0.25, 0.25, 0.5]

**Task list**
- [x] Review the current strategy space (GTCoalition, GTPlayer)
- [x] Review the coalition strategy, i.e. Concatenate (removed??), etc.
- [x] Introduce C_COALITION_CUSTOM?
- [ ] Update get_payoff() in GTPayoffMatrix, _get_evaluation() in GTGame. Is it still possible to use self._function??

**Related issues**
#...

**Cross references**
...
