### ISSUE TITLE
BF-ML: Extensions for Hyperparameter Updates 

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#784]
**Description/Motivation**
The model shall be reset/updated when new hyperparameters are set by the HPT.

**Task list**
- [x] 1. A new event handler method shall be implemented that handles the events raised for the Hyperparameter updates
- [x] 2. A new flag on the model level keeps track of the change and the need to update the model
- [x] 3. A new method update: when the flag is set to true, updates the model based on the new Hyperparams

**Related issues**
#...

**Cross references**
...
