### ISSUE TITLE
Bug: Review/correction of howtos

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#863]
**1 Describe the bug**
In issue #847 (branch howtos/refactoring) nearly all howtos were moved from ./doc/rtd/... to ./test/howtos (except GT and SL). Also the test script ./test/test_examples.py was refactored. It scans folder ./test/howtos for Python scripts and executes them. File information are logged accordingly. 

Files causing a dump were excluded from the test by adding the extension ".off" to the file name. These are logged in yellow.

Some of the files create log entries (white) that should be suppressed in dark mode.

![2023-09-25_12-47](https://github.com/fhswf/MLPro/assets/79243976/febd52e5-1d04-4fcf-959e-2857d5e62663)

**2 To Reproduce**
1. Open branch **howtos/refactoring**
2. Run script ./test/test_examples.py
3. Check yellow log lines for howtos of own responsibility
4. For each howto: remove the file extension ".off" and restart test_examples.py
5. Check the dump and eliminate the origin (please comment if you need assistance)
6. Check white log lines whether they can be suppressed

**3 Tasks (please tick off)**
- [x] Check/corrections Detlef
- [ ] Check/corrections Steve
- [ ] Check/corrections Laxmikant
- [ ] Check/corrections Syam

**Comment by detlefarend** [comment]
Hi guys, please don't use OpenML streams in howtos.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I shall update the related/affected howtos in this branch, right?

**Comment by detlefarend** [comment]
> Hi @detlefarend , I shall update the related/affected howtos in this branch, right?

Yes, please
