### ISSUE TITLE
Wrapper classes for OpenAI Gym/Petting Zoo: New method get_cycle_limit()

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#88]
The interface of class Environment has been extended by a new method **get_cycle_limit()** that returns the recommended cycle limit for training episodes. The method can be used to configure a proper training process.

In native env implementations it is a static value in the new internal constant C_CYCLE_LIMIT and has to be defined by the creator of a new env.

OpenAI Gym/Petting Zoo provide this value as well. So the new method get_cycle_limit() of the related wrapper classes can be implemented by returning this value from the env registry.

**Tasks:**
- [ ] Wrapper OpenAI Gym: implementation of method get_cycle_limits()
- [ ] Wrapper Petting Zoo: implementation of method get_cycle_limits()
- [ ] Adaption of related HowTo-files

**Requirements:**
Branch agent-and-env-model-improvements and the related issues.

**See also:** 
[Gym Registry](https://github.com/openai/gym/blob/master/gym/envs/__init__.py)
