### ISSUE TITLE
Refact: Consolidation of native streams

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#916]
**Motivation**
Removal of obsolete code and simplification/clarification of the related howto files.

**Tasks**
- [x] Replacement of obsolete native streams
   - [x] mlpro/bf/streams/streams/clouds2d_static.py
   - [x] mlpro/bf/streams/streams/clouds2d_dynamic.py
   - [x] mlpro/bf/streams/streams/clouds3d_static.py
   - [x] mlpro/bf/streams/streams/clouds3d_dynamic.py
 by a more general and flexible native stream
   - [x]  mlpro/bf/streams/streams/clouds.py
- [x] Cleanup and simplification of related howtos
- [x] Update of RTD documentation

**Benefit**
Elemination of redundant code and simplifaction of MLPro's benchmark stream structure.

**Are the proposed changes backward compatible?** 
- [ ] Yes
- [x] No
