### ISSUE TITLE
BF-Streams: New benchmark cluster generator based on CluGen

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#921]
**Description/Motivation**
Clugen is a benchmark cluster generator proposed bei [Fachada e.a. in 2023](https://doi.org/10.1016/j.knosys.2023.110836).

**Task list**
- [ ] 1. New wrapper/Integration repo for pyclugen
- [ ] 2. Howtos to demonstrate the use of pyclugen in online data streams

**Alternatively**
- [ ] Contact the authors and propose to provide pyclugen as MLPro extension

**Cross references**
[Paper "Generating multidimensional clusters with support lines"](https://doi.org/10.1016/j.knosys.2023.110836)
[Github Owner Glugen](https://github.com/clugen)
[Python implementation pyclugen](https://github.com/clugen/pyclugen)

**Comment by detlefarend** [comment]
@syamrajsatheesh fyi
