### ISSUE TITLE
OA-Streams-AD: Visualization of anomalies

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#926]
**Description/Motivation**
The possibilities of visualization of anomalies shall be examined and implemented. There are some specific aspects to be considered:
- Visualization is event-oriented
- Visualization depends on the anomaly type

**Task list**
- [x] 1. Basic strategy for event-oriented visualization
- [x] 2. Visualization for different types of anomalies
    - [x] 2.1 Point Outliers (Detlef)
    - [x] 2.2 Group Outliers (Syam)

**Related issues**
#...

**Cross references**
...
