### ISSUE TITLE
BF: General systematics for properties (and their derivatives)

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#943]
**Description/Motivation**
A systematics for general properties is required. Concrete aspects are:
- Management of properties and their values (and derivatives)

**Task list**
- [x] 1. New classes bf.data.Property, bf.data.Properties
- [x] 2. Howtos
    - [x] howto_bf_data_011_properties_with_implicite_time_index.py
    - [x] howto_bf_data_012_properties_with_explicite_integer_time_index.py
    - [x] howto_bf_data_013_properties_with_explicite_datetime_index.py

**Related issues**
#944 #945
