### ISSUE TITLE
WR: Wrapper for simpful (MLPro-Int-Simpful)

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#947]
**Description/Motivation**
Simpful is an open-source Python library for fuzzy inference rules. The wrapper is to use fuzzy inference systems as a policy that performs in RL environments and GT game boards.

**Task list**
- [ ] Create a new repository MLPro-Int-Simpful
- [ ] Develop a wrapper class for Simpful as policy (can be used for RL and GT) by also turning off its adaptivity
- [ ] Sample applications on BGLP's RL environment

**Related issues**
#...

**Cross references**
[Github Link](https://github.com/aresio/simpful/tree/master)
https://simpful.readthedocs.io/en/latest/
