### ISSUE TITLE
OA: Enhancements on cluster properties

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#959]
**Description/Motivation**
![PXL_20240503_123350452.jpg](https://github.com/fhswf/MLPro/assets/79243976/8a0261c7-9fa6-4b64-957f-4e82df853f46)

**Task list**
- [x] 1. Type aliased for property definitions
- [x] 2. Class Property
    - [x] Make internal attributes protected
- [ ] 3. Class ClusterAnalyzer
    - [x] Attribute C_CLUSTER_PROPERTIES = [ ] 
    - [ ] New method align_cluster_properties( p_properties : list )
          Aligns internal list of properties with given list of properties. In particular, the maximum derivative order shall be       taken over. Returns the list of unknown properties.

**Related issues**
#...

**Cross references**
...
