### ISSUE TITLE
BF-Streams: Basic Concept for Scaling

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#976]
**Description/Motivation**
A concept for scaling is needed to enable unscaling of scaled result data.

**Task list**
- [ ] 1. New root class bf.math.Scaler for all types of scaling including normalization
    - [ ] Methods scale, unscale, rescale
- [ ] 2. Class bf.math.Normalizer: new parent class bf.math.Scaler
- [ ] 3. Class StreamTask: new method unscale( p_inst )
      Unscales an instance by backpropagating all predecessor scalers... 
- [ ] 4. Class StreamWorkflow: new method unscale( p_inst )
      Unscales an instance by backpropagating all predecessor scalers... 
- [ ] 5. New class bf.streams.tasks.Scaler (parents: bf.streams.tasks.StreamTask, bf.math.Scaler)
      Scales  features of a stream with static factors

**Related issues**
#975
