### ISSUE TITLE
OA: Class OATask - Extension of adaption by new methods for pre- and postprocessing

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#983]
**Description/Motivation**
Class OATask shall be extended by further custom methods for pre- and postprocessing as part of adaptation.

**Task list**
- [x] 1. New custom method OATask._adapt_pre()
- [x] 2. New custom method OATask._adapt_post()
- [x] 3. Method OATask.adapt(): integration of new methods
